In [1]:
"""
Cricsheet IPL 2026 Data Loader
===============================
Loads IPL 2026 season data from a full Cricsheet IPL archive folder
and produces 4 clean dataframes/CSV files:
 
    players.csv    — one row per player (name + Cricsheet ID)
    matches.csv    — one row per match (venue, teams, result etc.)
    deliveries.csv — one row per ball bowled
    officials.csv - one row per official
 
Only matches with ID >= 1527674 are loaded (start of 2026 IPL season).
 
Usage:
    1. Set DATA_FOLDER to the path of your folder
    2. Run: python cricket_loader.py
"""

'\nCricsheet IPL 2026 Data Loader\n===============================\nLoads IPL 2026 season data from a full Cricsheet IPL archive folder\nand produces 4 clean dataframes/CSV files:\n\n    players.csv    — one row per player (name + Cricsheet ID)\n    matches.csv    — one row per match (venue, teams, result etc.)\n    deliveries.csv — one row per ball bowled\n    officials.csv - one row per official\n\nOnly matches with ID >= 1527674 are loaded (start of 2026 IPL season).\n\nUsage:\n    1. Set DATA_FOLDER to the path of your folder\n    2. Run: python cricket_loader.py\n'

### Import Python libraries and initialize constants

In [2]:
import pandas as pd
import os
import json 
import numpy as np 

IPL_DATA_FOLDER = "./ipl_male_json"
FIRST_2026_REG_SEASON_MATCH = 1527674
LAST_2026_REG_SEASON_MATCH = 1529313
FINAL_MATCH = 1535465
#pd.set_option('display.max_rows', None)

### Get 2026 Match IDs

In [3]:
def get_2026_match_IDs(folder_path):
    """
    Scans the folder for all delivery CSVs and returns only
    match IDs >= FIRST_2026_MATCH.
    """
    all_ids = []
    all_reg_season_ids = []
    all_playoff_ids = []

    for filename in os.listdir(folder_path):
        if filename.endswith(".json"):
            try:
                match_id = int(filename.replace(".json", ""))
                if match_id >= FIRST_2026_REG_SEASON_MATCH:
                    all_ids.append(match_id)
            except ValueError:
                pass  # skip any files that don't have a numeric name
 
    all_ids.sort()
    all_playoff_ids = all_ids[-4:]
    all_reg_season_ids = all_ids[:-4]
    return all_ids, all_reg_season_ids, all_playoff_ids

In [4]:
match_ids, reg_season_ids, playoff_ids = get_2026_match_IDs(IPL_DATA_FOLDER)
match_ids

[1527674,
 1527675,
 1527676,
 1527677,
 1527678,
 1527679,
 1527680,
 1527681,
 1527682,
 1527683,
 1527684,
 1527685,
 1527686,
 1527687,
 1527688,
 1527689,
 1527690,
 1527691,
 1527692,
 1527693,
 1529264,
 1529265,
 1529266,
 1529267,
 1529268,
 1529269,
 1529270,
 1529271,
 1529272,
 1529273,
 1529274,
 1529275,
 1529276,
 1529277,
 1529278,
 1529279,
 1529280,
 1529281,
 1529282,
 1529283,
 1529284,
 1529285,
 1529286,
 1529287,
 1529288,
 1529289,
 1529290,
 1529291,
 1529292,
 1529293,
 1529294,
 1529295,
 1529296,
 1529297,
 1529298,
 1529299,
 1529300,
 1529301,
 1529302,
 1529303,
 1529304,
 1529305,
 1529306,
 1529307,
 1529308,
 1529309,
 1529310,
 1529311,
 1529312,
 1529313,
 1535462,
 1535463,
 1535464,
 1535465]

In [5]:
reg_season_ids

[1527674,
 1527675,
 1527676,
 1527677,
 1527678,
 1527679,
 1527680,
 1527681,
 1527682,
 1527683,
 1527684,
 1527685,
 1527686,
 1527687,
 1527688,
 1527689,
 1527690,
 1527691,
 1527692,
 1527693,
 1529264,
 1529265,
 1529266,
 1529267,
 1529268,
 1529269,
 1529270,
 1529271,
 1529272,
 1529273,
 1529274,
 1529275,
 1529276,
 1529277,
 1529278,
 1529279,
 1529280,
 1529281,
 1529282,
 1529283,
 1529284,
 1529285,
 1529286,
 1529287,
 1529288,
 1529289,
 1529290,
 1529291,
 1529292,
 1529293,
 1529294,
 1529295,
 1529296,
 1529297,
 1529298,
 1529299,
 1529300,
 1529301,
 1529302,
 1529303,
 1529304,
 1529305,
 1529306,
 1529307,
 1529308,
 1529309,
 1529310,
 1529311,
 1529312,
 1529313]

In [6]:
playoff_ids

[1535462, 1535463, 1535464, 1535465]

### Get 2026 Match Reg Season Info

In [7]:
# -------------------------------------------------------
# STEP 2: Get match and player info for reg season
# -------------------------------------------------------
def load_match_info(folder, match_ids):
    """
    Reads .json for each 2026 match and returns:
      - matches_df : one row per match
      - players_df : unique player registry (name + Cricsheet ID)
      - officials_df: unique official registry
    """
    all_matches = []
    all_registry = []
    all_players = []
    all_officials = []
 
    for match_id in match_ids:
        filename = f"{match_id}.json"
        filepath = os.path.join(folder, filename)
        if not os.path.exists(filepath):
            print(f"  Warning: {filename} not found, skipping")
            continue
 
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                d = json.load(f)
 
            # --- Get registry info ------
            registry_people = d.get("info", {}).get("registry", {}).get("people",{})
 
            # --- Retrieve data for names and Cricsheet ID ---
            for player_name, cricsheet_id in registry_people.items():
                if player_name and cricsheet_id:
                    all_registry.append({
                        "player_name": player_name,
                        "id": cricsheet_id
                    })


            # ---Get player info ----
            player_data = d.get("info", {}).get("players", {})
            for team, player_list in player_data.items():
                if team and player_list:
                    for player in player_list:
                        all_players.append({
                            "player_name": player,
                            "team": team
                        })

            # --- Get match info ----
            match_data = d.get("info", {})
            match_city = match_data.get("city", "")
            match_dates = match_data.get("dates", [])
            match_date = match_dates[0] if match_dates else ""
            match_number = match_data.get("event", {}).get("match_number", str(0))

            outcome_data = match_data.get("outcome", {})
            match_winner = ""
            match_outcome = ""
            
            if "winner" in outcome_data:
                match_winner = outcome_data.get("winner", "")
                match_outcome = outcome_data.get("by", {})
                if "wickets" in match_outcome:
                    match_outcome_w_r = "wickets"
                    match_outcome_amt = match_outcome.get("wickets", str(0))
                elif "runs" in match_outcome:
                    match_outcome_w_r = "runs"
                    match_outcome_amt = match_outcome.get("runs", str(0))
            elif "eliminator" in outcome_data:
                match_winner = outcome_data.get("eliminator", "")
                match_outcome = outcome_data.get("result", "")
                match_outcome_w_r = ""
                match_outcome_amt = ""
            elif "result" in outcome_data:
                match_winner = "NR"
                match_outcome = outcome_data.get("result", "")
                match_outcome_w_r = ""
                match_outcome_amt = ""


            # --- Teams Logic ---
            teams = match_data.get("teams", [])
            team_1 = teams[0] if len(teams) > 0 else ""
            team_2 = teams[1] if len(teams) > 1 else ""

            match_toss_winner = match_data.get("toss", {}).get("winner", "")
            match_toss_decision = match_data.get("toss", {}).get("decision", "")
            match_venue = match_data.get("venue", "")

            all_matches.append({
                "match_id": match_id,
                "city": match_city,
                "date": match_date,
                "number": match_number,
                "winner": match_winner,
                "outcome": match_outcome,
                "wickets_runs": match_outcome_w_r,
                "winning_amount": match_outcome_amt,
                "toss_winner": match_toss_winner,
                "toss_decision": match_toss_decision,
                "venue": match_venue,
                "team1": team_1,
                "team2": team_2

            })
            
            #Get official info
            official_data = match_data.get("officials", {})
            match_referees = official_data.get("match_referees", [])
            match_referee = match_referees[0] if match_referees else ""
            reserve_umpires = official_data.get("reserve_umpires", [])
            reserve_umpire = reserve_umpires[0] if reserve_umpires else ""
            tv_umpires = official_data.get("tv_umpires", [])
            tv_umpire = tv_umpires[0] if tv_umpires else ""
            umpires = official_data.get("umpires", [])
            if umpires:
                umpire1 = umpires[0] 
                umpire2 = umpires[1]
                
            else:
                umpire1 = ""
                umpire2 = ""

            all_officials.append({
                "match_id": match_id,
                "match_referee": match_referee,
                "reserve_umpire": reserve_umpire,
                "tv_umpire": tv_umpire,
                "first_umpire": umpire1,
                "second_umpire": umpire2
            })
        
        except Exception as e:
            print(f"  Warning: could not load {filename} — {e}")
 
    matches_df = (pd.DataFrame(all_matches))
    #print(matches_df)
    officials_df = (pd.DataFrame(all_officials))
    registry_df = (pd.DataFrame(all_registry).drop_duplicates(subset="player_name"))
    #print(registry_df)                
    players_df = (pd.DataFrame(all_players).drop_duplicates(subset="player_name"))
    #print(team_df)
    players_id_df = (pd.merge(registry_df, players_df, on="player_name", how='left').sort_values("team").reset_index(drop=True))
 
    print(f"✓ Matches loaded:  {len(matches_df)}")
    print(f"✓ Players found:   {len(players_df)}")
    return matches_df, players_id_df, registry_df

In [8]:
def load_delivery_files(folder, match_ids):
    """
    Reads the ball-by-ball delivery CSV for each 2026 match.
    
    """
    all_deliveries = []
 
    #print(f"\nLoading delivery files...")
 
    for match_id in match_ids:
        filename = f"{match_id}.json"
        filepath = os.path.join(folder, filename)
 
        if not os.path.exists(filepath):
            print(f"  Warning: {filename} not found, skipping")
            continue
 
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                d = json.load(f)

            innings_data = d.get("innings", [])
            for innings in innings_data[:2]:
                team = innings.get("team", "")

                powerplays_data = innings.get("powerplays", [])
                powerplays_from = 0.0
                powerplays_to = 0.0
                powerplays_type = ""
                if powerplays_data:
                    powerplays_from = powerplays_data[0].get("from", 0.0)
                    powerplays_to = powerplays_data[0].get("to", 0.0)
                    powerplays_type = powerplays_data[0].get("type", "")

                for overs_data in innings.get("overs", []):
                    over = overs_data.get("over", -1)

                    for delivery in overs_data.get("deliveries", []):
                        actual_delivery = delivery.get("actual_delivery", "")
                        batsman = delivery.get("batter", "")
                        bowler = delivery.get("bowler", "")
                        extra_data = delivery.get("extras", {})
                        extra_type = ""
                        extra_value = 0
                        if extra_data:
                            for extra, value in extra_data.items():
                                extra_type = extra
                                
                        non_striker = delivery.get("non_striker", "")
                        batter_runs = delivery.get("runs", {}).get("batter", "")
                        extra_runs = delivery.get("runs", {}).get("extras", "")
                        total_runs = delivery.get("runs", {}).get("total", "")
                        review_by = delivery.get("review", {}).get("by", "")
                        review_umpire = delivery.get("review", {}).get("umpire", "")
                        review_batter = delivery.get("review", {}).get("batter", "")
                        review_decision = delivery.get("review", {}).get("decision", "")
                        review_type = delivery.get("review", {}).get("type", "")
                        wickets_data_list = delivery.get("wickets", [])
                        player_out = ""
                        wicket_fielder = []
                        wicket_fielder_name = ""
                        wicket_kind = ""
                        if wickets_data_list:
                            player_out = wickets_data_list[0].get("player_out", "")
                            wicket_fielder = wickets_data_list[0].get("fielders", [])
                            if wicket_fielder:
                                wicket_fielder_name = wicket_fielder[0].get("name", "")
                            wicket_kind = wickets_data_list[0].get("kind", "")
                        if (float(actual_delivery) >= powerplays_from) and (float(actual_delivery) <= powerplays_to):                       
                            powerplay_flag = 1
                            current_powerplay_type = powerplays_type
                        else:
                            powerplay_flag = 0
                            current_powerplay_type = ""
                        


                        all_deliveries.append({
                            "match_id":match_id,
                            "team": team,
                            "over": over,
                            "actual_delivery": actual_delivery,
                            "batsman": batsman,
                            "bowler": bowler,
                            "non_striker": non_striker,
                            "batter_runs": batter_runs,
                            "extra_type": extra_type,
                            "extra_runs": extra_runs,
                            "total_runs": total_runs,
                            "review_by": review_by,
                            "review_umpire": review_umpire,
                            "review_batter": review_batter,
                            "review_decision": review_decision,
                            "review_type": review_type,
                            "player_out": player_out,
                            "wicket_fielder": wicket_fielder_name,
                            "wicket_kind": wicket_kind,
                            "powerplay_flag": powerplay_flag,
                            "powerplays_type": current_powerplay_type
                                })
 
        except Exception as e:
            print(f"  Warning: could not load {filename} — {e}")
 
    deliveries_df = pd.DataFrame(all_deliveries)
    print(f"✓ Total deliveries loaded: {len(deliveries_df):,}")
    return deliveries_df

In [9]:
display(len(match_ids))

74

In [10]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
matches_df, players_df, registry_df= load_match_info(IPL_DATA_FOLDER, reg_season_ids)
matches_df

✓ Matches loaded:  70
✓ Players found:   201

,match_id,city,date,number,winner,outcome,wickets_runs,winning_amount,toss_winner,toss_decision,venue,team1,team2
0,1527674,Bengaluru,2026-03-28,1,Royal Challengers Bengaluru,{'wickets': 6},wickets,6,Royal Challengers Bengaluru,field,"M Chinnaswamy Stadium, Bengaluru",Sunrisers Hyderabad,Royal Challengers Bengaluru
1,1527675,Mumbai,2026-03-29,2,Mumbai Indians,{'wickets': 6},wickets,6,Mumbai Indians,field,"Wankhede Stadium, Mumbai",Kolkata Knight Riders,Mumbai Indians
2,1527676,Guwahati,2026-03-30,3,Rajasthan Royals,{'wickets': 8},wickets,8,Rajasthan Royals,field,"Barsapara Cricket Stadium, Guwahati",Chennai Super Kings,Rajasthan Royals
3,1527677,New Chandigarh,2026-03-31,4,Punjab Kings,{'wickets': 3},wickets,3,Punjab Kings,field,Maharaja Yadavindra Singh International Cricke...,Gujarat Titans,Punjab Kings
4,1527678,Lucknow,2026-04-01,5,Delhi Capitals,{'wickets': 6},wickets,6,Delhi Capitals,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Delhi Capitals
5,1527679,Kolkata,2026-04-02,6,Sunrisers Hyderabad,{'runs': 65},runs,65,Kolkata Knight Riders,field,"Eden Gardens, Kolkata",Sunrisers Hyderabad,Kolkata Knight Riders
6,1527680,Chennai,2026-04-03,7,Punjab Kings,{'wickets': 5},wickets,5,Punjab Kings,field,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai Super Kings,Punjab Kings
7,1527681,Delhi,2026-04-04,8,Delhi Capitals,{'wickets': 6},wickets,6,Delhi Capitals,field,"Arun Jaitley Stadium, Delhi",Mumbai Indians,Delhi Capitals
8,1527682,Ahmedabad,2026-04-04,9,Rajasthan Royals,{'runs': 6},runs,6,Rajasthan Royals,bat,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,Gujarat Titans
9,1527683,Hyderabad,2026-04-05,10,Lucknow Super Giants,{'wickets': 5},wickets,5,Lucknow Super Giants,field,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Lucknow Super Giants
10,1527684,Bengaluru,2026-04-05,11,Royal Challengers Bengaluru,{'runs': 43},runs,43,Chennai Super Kings,field,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bengaluru,Chennai Super Kings
11,1527685,Kolkata,2026-04-06,12,NR,no result,,,Kolkata Knight Riders,bat,"Eden Gardens, Kolkata",Kolkata Knight Riders,Punjab Kings
12,1527686,Guwahati,2026-04-07,13,Rajasthan Royals,{'runs': 27},runs,27,Mumbai Indians,field,"Barsapara Cricket Stadium, Guwahati",Rajasthan Royals,Mumbai Indians
13,1527687,Delhi,2026-04-08,14,Gujarat Titans,{'runs': 1},runs,1,Delhi Capitals,field,"Arun Jaitley Stadium, Delhi",Gujarat Titans,Delhi Capitals
14,1527688,Kolkata,2026-04-09,15,Lucknow Super Giants,{'wickets': 3},wickets,3,Lucknow Super Giants,field,"Eden Gardens, Kolkata",Kolkata Knight Riders,Lucknow Super Giants
15,1527689,Guwahati,2026-04-10,16,Rajasthan Royals,{'wickets': 6},wickets,6,Rajasthan Royals,field,"Barsapara Cricket Stadium, Guwahati",Royal Challengers Bengaluru,Rajasthan Royals
16,1527690,New Chandigarh,2026-04-11,17,Punjab Kings,{'wickets': 6},wickets,6,Punjab Kings,field,Maharaja Yadavindra Singh International Cricke...,Sunrisers Hyderabad,Punjab Kings
17,1527691,Chennai,2026-04-11,18,Chennai Super Kings,{'runs': 23},runs,23,Delhi Capitals,field,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai Super Kings,Delhi Capitals
18,1527692,Lucknow,2026-04-12,19,Gujarat Titans,{'wickets': 7},wickets,7,Gujarat Titans,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Gujarat Titans
19,1527693,Mumbai,2026-04-12,20,Royal Challengers Bengaluru,{'runs': 18},runs,18,Mumbai Indians,field,"Wankhede Stadium, Mumbai",Royal Challengers Bengaluru,Mumbai Indians
20,1529264,Hyderabad,2026-04-13,21,Sunrisers Hyderabad,{'runs': 57},runs,57,Rajasthan Royals,field,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Rajasthan Royals
21,1529265,Chennai,2026-04-14,22,Chennai Super Kings,{'runs': 32},runs,32,Kolkata Knight Riders,field,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai Super Kings,Kolkata Knight Riders
22,1529266,Bengaluru,2026-04-15,23,Royal Challengers Bengaluru,{'wickets': 5},wickets,5,Royal Challengers Bengaluru,field,"M Chinnaswamy Stadium, Bengaluru",Lucknow Super Giants,Royal Challengers Bengaluru
23,1529267,Mumbai,2026-04-16,24,Punjab Kings,{'wickets': 7},wickets,7,Punjab Kings,field,"Wankhede Stadium, Mumbai",Mumbai Indians,Punjab Kings
24,1529268,Ahmedabad,2026-04-17,25,Gujarat Titans,{'wickets': 5},wickets,5,Kolkata Knight Riders,bat,"Narendra Modi Stadium, Ahmedabad",Kolkata Knight Riders,Gujarat Titans
25,1529269,Bengaluru,2026-04-18,26,Delhi Capitals,{'wickets': 6},wickets,6,Delhi Capitals,field,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bengaluru,Delhi Capitals
26,1529270,Hyderabad,2026-04-18,27,Sunrisers Hyderabad,{'runs': 10},runs,10,Chennai Super Kings,field,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Chennai Super Kings
27,1529271,Kolkata,2026-04-19,28,Kolkata Knight Riders,{'wickets': 4},wickets,4,Rajasthan Royals,bat,"Eden Gardens, Kolkata",Rajasthan Royals,Kolkata Knight Riders
28,1529272,New Chandigarh,2026-04-19,29,Punjab Kings,{'runs': 54},runs,54,Lucknow Super Giants,field,Maharaja Yadavindra Singh International Cricke...,Punjab Kings,Lucknow Super Giants
29,1529273,Ahmedabad,2026-04-20,30,Mumbai Indians,{'runs': 99},runs,99,Gujarat Titans,field,"Narendra Modi Stadium, Ahmedabad",Mumbai Indians,Gujarat Titans
30,1529274,Hyderabad,2026-04-21,31,Sunrisers Hyderabad,{'runs': 47},runs,47,Delhi Capitals,field,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Delhi Capitals
31,1529275,Lucknow,2026-04-22,32,Rajasthan Royals,{'runs': 40},runs,40,Lucknow Super Giants,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Rajasthan Royals,Lucknow Super Giants
32,1529276,Mumbai,2026-04-23,33,Chennai Super Kings,{'runs': 103},runs,103,Mumbai Indians,field,"Wankhede Stadium, Mumbai",Chennai Super Kings,Mumbai Indians
33,1529277,Bengaluru,2026-04-24,34,Royal Challengers Bengaluru,{'wickets': 5},wickets,5,Royal Challengers Bengaluru,field,"M Chinnaswamy Stadium, Bengaluru",Gujarat Titans,Royal Challengers Bengaluru
34,1529278,Delhi,2026-04-25,35,Punjab Kings,{'wickets': 6},wickets,6,Delhi Capitals,bat,"Arun Jaitley Stadium, Delhi",Delhi Capitals,Punjab Kings
35,1529279,Jaipur,2026-04-25,36,Sunrisers Hyderabad,{'wickets': 5},wickets,5,Sunrisers Hyderabad,field,"Sawai Mansingh Stadium, Jaipur",Rajasthan Royals,Sunrisers Hyderabad
36,1529280,Chennai,2026-04-26,37,Gujarat Titans,{'wickets': 8},wickets,8,Gujarat Titans,field,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai Super Kings,Gujarat Titans
37,1529281,Lucknow,2026-04-26,38,Kolkata Knight Riders,tie,,,Lucknow Super Giants,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Kolkata Knight Riders,Lucknow Super Giants
38,1529282,Delhi,2026-04-27,39,Royal Challengers Bengaluru,{'wickets': 9},wickets,9,Royal Challengers Bengaluru,field,"Arun Jaitley Stadium, Delhi",Delhi Capitals,Royal Challengers Bengaluru
39,1529283,New Chandigarh,2026-04-28,40,Rajasthan Royals,{'wickets': 6},wickets,6,Rajasthan Royals,field,Maharaja Yadavindra Singh International Cricke...,Punjab Kings,Rajasthan Royals
40,1529284,Mumbai,2026-04-29,41,Sunrisers Hyderabad,{'wickets': 6},wickets,6,Mumbai Indians,bat,"Wankhede Stadium, Mumbai",Mumbai Indians,Sunrisers Hyderabad
41,1529285,Ahmedabad,2026-04-30,42,Gujarat Titans,{'wickets': 4},wickets,4,Gujarat Titans,field,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Gujarat Titans
42,1529286,Jaipur,2026-05-01,43,Delhi Capitals,{'wickets': 7},wickets,7,Rajasthan Royals,bat,"Sawai Mansingh Stadium, Jaipur",Rajasthan Royals,Delhi Capitals
43,1529287,Chennai,2026-05-02,44,Chennai Super Kings,{'wickets': 8},wickets,8,Mumbai Indians,bat,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,Chennai Super Kings
44,1529288,Hyderabad,2026-05-03,45,Kolkata Knight Riders,{'wickets': 7},wickets,7,Sunrisers Hyderabad,bat,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Kolkata Knight Riders
45,1529289,Ahmedabad,2026-05-03,46,Gujarat Titans,{'wickets': 4},wickets,4,Gujarat Titans,field,"Narendra Modi Stadium, Ahmedabad",Punjab Kings,Gujarat Titans
46,1529290,Mumbai,2026-05-04,47,Mumbai Indians,{'wickets': 6},wickets,6,Mumbai Indians,field,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Mumbai Indians
47,1529291,Delhi,2026-05-05,48,Chennai Super Kings,{'wickets': 8},wickets,8,Delhi Capitals,bat,"Arun Jaitley Stadium, Delhi",Delhi Capitals,Chennai Super Kings
48,1529292,Hyderabad,2026-05-06,49,Sunrisers Hyderabad,{'runs': 33},runs,33,Punjab Kings,field,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Punjab Kings
49,1529293,Lucknow,2026-05-07,50,Lucknow Super Giants,{'runs': 9},runs,9,Royal Challengers Bengaluru,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Royal Challengers Bengaluru
50,1529294,Delhi,2026-05-08,51,Kolkata Knight Riders,{'wickets': 8},wickets,8,Kolkata Knight Riders,field,"Arun Jaitley Stadium, Delhi",Delhi Capitals,Kolkata Knight Riders
51,1529295,Jaipur,2026-05-09,52,Gujarat Titans,{'runs': 77},runs,77,Rajasthan Royals,field,"Sawai Mansingh Stadium, Jaipur",Gujarat Titans,Rajasthan Royals
52,1529296,Chennai,2026-05-10,53,Chennai Super Kings,{'wickets': 5},wickets,5,Chennai Super Kings,field,"MA Chidambaram Stadium, Chepauk, Chennai",Lucknow Super Giants,Chennai Super Kings
53,1529297,Raipur,2026-05-10,54,Royal Challengers Bengaluru,{'wickets': 2},wickets,2,Royal Challengers Bengaluru,field,Shaheed Veer Narayan Singh International Stadi...,Mumbai Indians,Royal Challengers Bengaluru
54,1529298,Dharamsala,2026-05-11,55,Delhi Capitals,{'wickets': 3},wickets,3,Delhi Capitals,field,"Himachal Pradesh Cricket Association Stadium, ...",Punjab Kings,Delhi Capitals
55,1529299,Ahmedabad,2026-05-12,56,Gujarat Titans,{'runs': 82},runs,82,Sunrisers Hyderabad,field,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Sunrisers Hyderabad
56,1529300,Raipur,2026-05-13,57,Royal Challengers Bengaluru,{'wickets': 6},wickets,6,Royal Challengers Bengaluru,field,Shaheed Veer Narayan Singh International Stadi...,Kolkata Knight Riders,Royal Challengers Bengaluru
57,1529301,Dharamsala,2026-05-14,58,Mumbai Indians,{'wickets': 6},wickets,6,Mumbai Indians,field,"Himachal Pradesh Cricket Association Stadium, ...",Punjab Kings,Mumbai Indians
58,1529302,Lucknow,2026-05-15,59,Lucknow Super Giants,{'wickets': 7},wickets,7,Lucknow Super Giants,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Chennai Super Kings,Lucknow Super Giants
59,1529303,Kolkata,2026-05-16,60,Kolkata Knight Riders,{'runs': 29},runs,29,Gujarat Titans,field,"Eden Gardens, Kolkata",Kolkata Knight Riders,Gujarat Titans
60,1529304,Dharamsala,2026-05-17,61,Royal Challengers Bengaluru,{'runs': 23},runs,23,Punjab Kings,field,"Himachal Pradesh Cricket Association Stadium, ...",Royal Challengers Bengaluru,Punjab Kings
61,1529305,Delhi,2026-05-17,62,Delhi Capitals,{'wickets': 5},wickets,5,Delhi Capitals,field,"Arun Jaitley Stadium, Delhi",Rajasthan Royals,Delhi Capitals
62,1529306,Chennai,2026-05-18,63,Sunrisers Hyderabad,{'wickets': 5},wickets,5,Chennai Super Kings,bat,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai Super Kings,Sunrisers Hyderabad
63,1529307,Jaipur,2026-05-19,64,Rajasthan Royals,{'wickets': 7},wickets,7,Rajasthan Royals,field,"Sawai Mansingh Stadium, Jaipur",Lucknow Super Giants,Rajasthan Royals
64,1529308,Kolkata,2026-05-20,65,Kolkata Knight Riders,{'wickets': 4},wickets,4,Kolkata Knight Riders,field,"Eden Gardens, Kolkata",Mumbai Indians,Kolkata Knight Riders
65,1529309,Ahmedabad,2026-05-21,66,Gujarat Titans,{'runs': 89},runs,89,Chennai Super Kings,field,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Chennai Super Kings
66,1529310,Hyderabad,2026-05-22,67,Sunrisers Hyderabad,{'runs': 55},runs,55,Sunrisers Hyderabad,bat,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Royal Challengers Bengaluru
67,1529311,Lucknow,2026-05-23,68,Punjab Kings,{'wickets': 7},wickets,7,Punjab Kings,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Punjab Kings
68,1529312,Mumbai,2026-05-24,69,Rajasthan Royals,{'runs': 30},runs,30,Mumbai Indians,field,"Wankhede Stadium, Mumbai",Rajasthan Royals,Mumbai Indians
69,1529313,Kolkata,2026-05-24,70,Delhi Capitals,{'runs': 40},runs,40,Kolkata Knight Riders,field,"Eden Gardens, Kolkata",Delhi Capitals,Kolkata Knight Riders

In [11]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(players_df)

               player_name        id                         team
0                 A Kamboj  fcc21ace          Chennai Super Kings
1                 A Mhatre  b2b4f545          Chennai Super Kings
2                J Overton  59559bc2          Chennai Super Kings
3                 KK Ahmed  a2f46292          Chennai Super Kings
4            Kartik Sharma  7b679de5          Chennai Super Kings
5                 MJ Henry  e84ac20c          Chennai Super Kings
6                 MW Short  a90e53ec          Chennai Super Kings
7               Noor Ahmad  efc04be7          Chennai Super Kings
8               RD Gaikwad  45a43fe2          Chennai Super Kings
9                   S Dube  a4e37e47          Chennai Super Kings
10                 SN Khan  f088b960          Chennai Super Kings
11               SV Samson  a4cc73aa          Chennai Super Kings
12                 PR Veer  e148e6bd          Chennai Super Kings
13               RD Chahar  2ed569a0          Chennai Super Kings
14               AJ Hosein  4d7f517e          Chennai Super Kings
15                D Brevis  844e79d1          Chennai Super Kings
16        Gurjapneet Singh  cc61ee8f          Chennai Super Kings
17        Mukesh Choudhary  765a4731          Chennai Super Kings
18             Urvil Patel  cf59b3f0          Chennai Super Kings
19                RS Ghosh  dee07622          Chennai Super Kings
20              SH Johnson  83c3e8e3          Chennai Super Kings
21                AR Patel  2e171977               Delhi Capitals
22               DA Miller  d67d5f00               Delhi Capitals
23                KL Rahul  b17e2f24               Delhi Capitals
24           Kuldeep Yadav  8d2c70ad               Delhi Capitals
25                 L Ngidi  f834dcfc               Delhi Capitals
26            Mukesh Kumar  2cffab74               Delhi Capitals
27                  N Rana  fb2d1dda               Delhi Capitals
28              P Nissanka  8ee36b18               Delhi Capitals
29            Sameer Rizvi  f89d3b11               Delhi Capitals
30             T Natarajan  ce794613               Delhi Capitals
31                T Stubbs  85b3fab2               Delhi Capitals
32                 V Nigam  5ffc0565               Delhi Capitals
33         Ashutosh Sharma  84d9c311               Delhi Capitals
34              Auqib Nabi  7c3c0337               Delhi Capitals
35                 KK Nair  944533a5               Delhi Capitals
36           Abishek Porel  ad3b6e95               Delhi Capitals
37             KA Jamieson  68c56d09               Delhi Capitals
38            PVD Chameera  327b58d3               Delhi Capitals
39               SU Parakh  926c7443               Delhi Capitals
40                MA Starc  3fb19989               Delhi Capitals
41                M Tiwari  fb5f69e4               Delhi Capitals
42                 T Vijay  51ec3919               Delhi Capitals
43            Ashok Sharma  50c09020               Gujarat Titans
44         B Sai Sudharsan  d5130a30               Gujarat Titans
45             GD Phillips  9a46c4e5               Gujarat Titans
46              JC Buttler  99b75528               Gujarat Titans
47                K Rabada  e62dd25d               Gujarat Titans
48       M Prasidh Krishna  85e0cf10               Gujarat Titans
49         M Shahrukh Khan  7dcb9bc9               Gujarat Titans
50          Mohammed Siraj  2f49c897               Gujarat Titans
51               R Tewatia  39a2dfa8               Gujarat Titans
52             Rashid Khan  5f547c8b               Gujarat Titans
53            Shubman Gill  b4b99816               Gujarat Titans
54       Washington Sundar  f19ccfad               Gujarat Titans
55          Kumar Kushagra  57ca01b3               Gujarat Titans
56               JO Holder  0f721006               Gujarat Titans
57               MJ Suthar  025c4400               Gujarat Titans
58             Arshad Khan  12314277               Gujarat Titans
59                N Sindhu  3cea23da               Gujarat Titans
60           R Sai Kishore  c7a995d3               Gujarat Titans
61           A Raghuvanshi  d7017798        Kolkata Knight Riders
62               AM Rahane  29e95537        Kolkata Knight Riders
63                  AS Roy  e4cdf230        Kolkata Knight Riders
64            B Muzarabani  449f4e3c        Kolkata Knight Riders
65                 C Green  eaa76d3c        Kolkata Knight Riders
66                CV Varun  5b7ab5a9        Kolkata Knight Riders
67                FH Allen  bf74b130        Kolkata Knight Riders
68            Kartik Tyagi  5d2eea49        Kolkata Knight Riders
69               MK Pandey  93b4fc78        Kolkata Knight Riders
70                RK Singh  0a509d6b        Kolkata Knight Riders
71         Ramandeep Singh  be24ead0        Kolkata Knight Riders
72               SP Narine  9d430b40        Kolkata Knight Riders
73                VG Arora  7c3b3b78        Kolkata Knight Riders
74           Navdeep Saini  21d4e29b        Kolkata Knight Riders
75                R Powell  650d5e49        Kolkata Knight Riders
76              TL Seifert  4663bd23        Kolkata Knight Riders
77                SR Dubey  11061889        Kolkata Knight Riders
78             M Pathirana  64839cb3        Kolkata Knight Riders
79                T Dahiya  f12fe2a1        Kolkata Knight Riders
80                A Badoni  872b03f7         Lucknow Super Giants
81                A Nortje  acdc62f5         Lucknow Super Giants
82              AK Markram  6a26221c         Lucknow Super Giants
83             Abdul Samad  8e514b4c         Lucknow Super Giants
84            MD Choudhary  1c84109e         Lucknow Super Giants
85                MR Marsh  3d8feaf8         Lucknow Super Giants
86          Mohammed Shami  8cf9814c         Lucknow Super Giants
87             Mohsin Khan  c33d8116         Lucknow Super Giants
88                N Pooran  3241e3fd         Lucknow Super Giants
89            Prince Yadav  80b2fb19         Lucknow Super Giants
90                 RR Pant  919a3be2         Lucknow Super Giants
91           Shahbaz Ahmed  f9e6e7ef         Lucknow Super Giants
92              Avesh Khan  eef2536f         Lucknow Super Giants
93                DS Rathi  13fc5c6d         Lucknow Super Giants
94             M Siddharth  cf0ccafa         Lucknow Super Giants
95                GF Linde  e5437608         Lucknow Super Giants
96            Himmat Singh  ebcfef83         Lucknow Super Giants
97                MP Yadav  b1ad996b         Lucknow Super Giants
98      Akshat Raghuwanshi  d8d67045         Lucknow Super Giants
99               JP Inglis  989889ff         Lucknow Super Giants
100            AA Kulkarni  2d140b79         Lucknow Super Giants
101            Akash Singh  b483905d         Lucknow Super Giants
102        Arjun Tendulkar  44aac2f0         Lucknow Super Giants
103           AM Ghazanfar  9ca68676               Mumbai Indians
104              HH Pandya  dbe50b21               Mumbai Indians
105              JJ Bumrah  462411b3               Mumbai Indians
106             M Markande  a9fd84fb               Mumbai Indians
107             Naman Dhir  fffa744b               Mumbai Indians
108           RD Rickelton  e66732f8               Mumbai Indians
109              RG Sharma  740742ef               Mumbai Indians
110               SA Yadav  271f83cd               Mumbai Indians
111          SE Rutherford  d014d5ac               Mumbai Indians
112              SN Thakur  1abb78f8               Mumbai Indians
113               TA Boult  a818c1be               Mumbai Indians
114            Tilak Varma  b0482a1d               Mumbai Indians
115                C Bosch  172dff15               Mumbai Indians
116              DL Chahar  23eeb873               Mumbai Indians
117             MJ Santner  e4a0deae               Mumbai Indians
118           Mayank Rawat  2b801189               Mumbai Indians
119              Q de Kock  372455c4               Mumbai Indians
120          Ashwani Kumar  d45c29b1               Mumbai Indians
121             DV Malewar  9e6032fa               Mumbai Indians
122           Krish Bhagat  e48a4814               Mumbai Indians
123                RA Bawa  ba6b2f91               Mumbai Indians
124                 R Minz  bafd0398               Mumbai Indians
125               WG Jacks  9caf69a1               Mumbai Indians
126           Raghu Sharma  5b615e7c               Mumbai Indians
127         Arshdeep Singh  244048f6                 Punjab Kings
128             C Connolly  fe366f34                 Punjab Kings
129               M Jansen  81c36ee9                 Punjab Kings
130             MP Stoinis  d9273ee7                 Punjab Kings
131              N Wadhera  d1a60072                 Punjab Kings
132         P Simran Singh  9418198b                 Punjab Kings
133          Priyansh Arya  b5797845                 Punjab Kings
134                SS Iyer  85ec8e33                 Punjab Kings
135         Shashank Singh  26989d80                 Punjab Kings
136      Vijaykumar Vyshak  54e52590                 Punjab Kings
137            XC Bartlett  3b53243a                 Punjab Kings
138              YS Chahal  57ee1fde                 Punjab Kings
139          Harpreet Brar  c05edf8e                 Punjab Kings
140            LH Ferguson  2f9d0389                 Punjab Kings
141        Suryansh Shedge  970ddd24                 Punjab Kings
142           BJ Dwarshuis  e1b9f3a9                 Punjab Kings
143            Yash Thakur  4b31f3a3                 Punjab Kings
144     Azmatullah Omarzai  8f6dd463                 Punjab Kings
145           Vishnu Vinod  0494fa6e                 Punjab Kings
146         Brijesh Sharma  133bbd61             Rajasthan Royals
147            Dhruv Jurel  bcf325d2             Rajasthan Royals
148              JC Archer  5574750c             Rajasthan Royals
149               N Burger  465aa633             Rajasthan Royals
150                R Parag  04a418e8             Rajasthan Royals
151              RA Jadeja  fe93fd9d             Rajasthan Royals
152           Ravi Bishnoi  df064e1a             Rajasthan Royals
153             SO Hetmyer  48a1d7b7             Rajasthan Royals
154         Sandeep Sharma  ce820073             Rajasthan Royals
155          V Suryavanshi  470f446b             Rajasthan Royals
156            YBK Jaiswal  6c19c6e5             Rajasthan Royals
157             D Ferreira  f0af99a7             Rajasthan Royals
158           TU Deshpande  46a9bea1             Rajasthan Royals
159           LG Pretorius  60aa2db3             Rajasthan Royals
160         Yash Raj Punja  02dfebbe             Rajasthan Royals
161             Ravi Singh  548516a6             Rajasthan Royals
162               SB Dubey  6b2ff18f             Rajasthan Royals
163             MD Shanaka  3ff033bb             Rajasthan Royals
164               AF Milne  350bb1b1             Rajasthan Royals
165              SS Mishra  92500ad5             Rajasthan Royals
166       Abhinandan Singh  82c10dac  Royal Challengers Bengaluru
167                B Kumar  2e81a32d  Royal Challengers Bengaluru
168             D Padikkal  2c25d4f5  Royal Challengers Bengaluru
169               JA Duffy  dadbdb68  Royal Challengers Bengaluru
170              JM Sharma  800d2d97  Royal Challengers Bengaluru
171              KH Pandya  5b8c830e  Royal Challengers Bengaluru
172                PD Salt  3d284ca3  Royal Challengers Bengaluru
173             R Shepherd  c5aef772  Royal Challengers Bengaluru
174             RM Patidar  c740ea83  Royal Challengers Bengaluru
175          Suyash Sharma  9440ef41  Royal Challengers Bengaluru
176               TH David  f1f99156  Royal Challengers Bengaluru
177                V Kohli  ba607b88  Royal Challengers Bengaluru
178             JG Bethell  3c55c703  Royal Challengers Bengaluru
179           JR Hazlewood  03806cf8  Royal Challengers Bengaluru
180                VR Iyer  a24be938  Royal Challengers Bengaluru
181           Rasikh Salam  b8527c3d  Royal Challengers Bengaluru
182        Abhishek Sharma  f29185a1          Sunrisers Hyderabad
183           Aniket Verma  a3b0600d          Sunrisers Hyderabad
184               DA Payne  6c79c098          Sunrisers Hyderabad
185              E Malinga  5750bcb4          Sunrisers Hyderabad
186              H Klaasen  235c2bb6          Sunrisers Hyderabad
187               HV Patel  f986ca1a          Sunrisers Hyderabad
188            Harsh Dubey  25228673          Sunrisers Hyderabad
189           Ishan Kishan  752f7486          Sunrisers Hyderabad
190             JD Unadkat  1e66c162          Sunrisers Hyderabad
191    Nithish Kumar Reddy  aad0c365          Sunrisers Hyderabad
192                S Arora  d7423da1          Sunrisers Hyderabad
193                TM Head  12b610c2          Sunrisers Hyderabad
194          Shivang Kumar  7b44eb3e          Sunrisers Hyderabad
195         LS Livingstone  50c6bc2b          Sunrisers Hyderabad
196               PP Hinge  ece7b6b3          Sunrisers Hyderabad
197          Sakib Hussain  280fff14          Sunrisers Hyderabad
198           D Madushanka  de7d833e          Sunrisers Hyderabad
199             PJ Cummins  ded9240e          Sunrisers Hyderabad
200               R Smaran  c1e53c3f          Sunrisers Hyderabad
201              A Bengeri  c109497d                          NaN
202          J Madanagopal  8275b04a                          NaN
203              J Srinath  bad31fac                          NaN
204               R Pandit  8a604384                          NaN
205              UV Gandhe  43dd4011                          NaN
206     Anish Sahasrabudhe  2892df67                          NaN
207   MV Saidharshan Kumar  54b6007b                          NaN
208            Nitin Menon  e1d41d9e                          NaN
209           Shakti Singh  eb90d319                          NaN
210           Vinod Seshan  a3357a27                          NaN
211        HDPK Dharmasena  323e4c16                          NaN
212         K Swaroopanand  aa2a4962                          NaN
213           M Krishnadas  e298c588                          NaN
214        V Narayan Kutty  4bacee3d                          NaN
215              VK Sharma  a7a49df4                          NaN
216                A Totre  b1d7d7bc                          NaN
217   Abhijit Bhattacharya  59ec9638                          NaN
218  KN Ananthapadmanabhan  3144063a                          NaN
219                P Joshi  ffc0e370                          NaN
220          Prakash Bhatt  f848ab0b                          NaN
221           AT Holdstock  6fa3258c                          NaN
222          Bhavesh Patel  ee03dc30                          NaN
223             HAS Khalid  291ded7c                          NaN
224               K Kelkar  1d88908d                          NaN
225               AK Argal  0ee78cf3                          NaN
226              Amit Rana  f5db088b                          NaN
227            Amit Sharma  7ea3e0cc                          NaN
228              KM Gandhi  a9421c64                          NaN
229          TM Srivastava  a76d10ba                          NaN
230            SJ Nogajski  9b3f9323                          NaN
231            IR Siddiqui  6436f803                          NaN
232                 R Seth  540a44ba                          NaN
233             P Dharmani  eaa90ab4                          NaN
234               T Ematty  e995f8e9                          NaN
235             DS Manohar  b35f3ac8                          NaN
236                P Dubey  ed5a5510                          NaN
237         A Kripal Singh  8f559207                          NaN
238                 JM Cox  ff154ecd                          NaN

In [12]:
officials_df = players_df[players_df['team'].isna()]
officials_df

               player_name        id team
201              A Bengeri  c109497d  NaN
202          J Madanagopal  8275b04a  NaN
203              J Srinath  bad31fac  NaN
204               R Pandit  8a604384  NaN
205              UV Gandhe  43dd4011  NaN
206     Anish Sahasrabudhe  2892df67  NaN
207   MV Saidharshan Kumar  54b6007b  NaN
208            Nitin Menon  e1d41d9e  NaN
209           Shakti Singh  eb90d319  NaN
210           Vinod Seshan  a3357a27  NaN
211        HDPK Dharmasena  323e4c16  NaN
212         K Swaroopanand  aa2a4962  NaN
213           M Krishnadas  e298c588  NaN
214        V Narayan Kutty  4bacee3d  NaN
215              VK Sharma  a7a49df4  NaN
216                A Totre  b1d7d7bc  NaN
217   Abhijit Bhattacharya  59ec9638  NaN
218  KN Ananthapadmanabhan  3144063a  NaN
219                P Joshi  ffc0e370  NaN
220          Prakash Bhatt  f848ab0b  NaN
221           AT Holdstock  6fa3258c  NaN
222          Bhavesh Patel  ee03dc30  NaN
223             HAS Khalid  291ded7c  NaN
224               K Kelkar  1d88908d  NaN
225               AK Argal  0ee78cf3  NaN
226              Amit Rana  f5db088b  NaN
227            Amit Sharma  7ea3e0cc  NaN
228              KM Gandhi  a9421c64  NaN
229          TM Srivastava  a76d10ba  NaN
230            SJ Nogajski  9b3f9323  NaN
231            IR Siddiqui  6436f803  NaN
232                 R Seth  540a44ba  NaN
233             P Dharmani  eaa90ab4  NaN
234               T Ematty  e995f8e9  NaN
235             DS Manohar  b35f3ac8  NaN
236                P Dubey  ed5a5510  NaN
237         A Kripal Singh  8f559207  NaN
238                 JM Cox  ff154ecd  NaN

In [13]:
players_df = players_df[(players_df['team']).notna()]
players_df

             player_name        id                         team
0               A Kamboj  fcc21ace          Chennai Super Kings
1               A Mhatre  b2b4f545          Chennai Super Kings
2              J Overton  59559bc2          Chennai Super Kings
3               KK Ahmed  a2f46292          Chennai Super Kings
4          Kartik Sharma  7b679de5          Chennai Super Kings
5               MJ Henry  e84ac20c          Chennai Super Kings
6               MW Short  a90e53ec          Chennai Super Kings
7             Noor Ahmad  efc04be7          Chennai Super Kings
8             RD Gaikwad  45a43fe2          Chennai Super Kings
9                 S Dube  a4e37e47          Chennai Super Kings
10               SN Khan  f088b960          Chennai Super Kings
11             SV Samson  a4cc73aa          Chennai Super Kings
12               PR Veer  e148e6bd          Chennai Super Kings
13             RD Chahar  2ed569a0          Chennai Super Kings
14             AJ Hosein  4d7f517e          Chennai Super Kings
15              D Brevis  844e79d1          Chennai Super Kings
16      Gurjapneet Singh  cc61ee8f          Chennai Super Kings
17      Mukesh Choudhary  765a4731          Chennai Super Kings
18           Urvil Patel  cf59b3f0          Chennai Super Kings
19              RS Ghosh  dee07622          Chennai Super Kings
20            SH Johnson  83c3e8e3          Chennai Super Kings
21              AR Patel  2e171977               Delhi Capitals
22             DA Miller  d67d5f00               Delhi Capitals
23              KL Rahul  b17e2f24               Delhi Capitals
24         Kuldeep Yadav  8d2c70ad               Delhi Capitals
25               L Ngidi  f834dcfc               Delhi Capitals
26          Mukesh Kumar  2cffab74               Delhi Capitals
27                N Rana  fb2d1dda               Delhi Capitals
28            P Nissanka  8ee36b18               Delhi Capitals
29          Sameer Rizvi  f89d3b11               Delhi Capitals
30           T Natarajan  ce794613               Delhi Capitals
31              T Stubbs  85b3fab2               Delhi Capitals
32               V Nigam  5ffc0565               Delhi Capitals
33       Ashutosh Sharma  84d9c311               Delhi Capitals
34            Auqib Nabi  7c3c0337               Delhi Capitals
35               KK Nair  944533a5               Delhi Capitals
36         Abishek Porel  ad3b6e95               Delhi Capitals
37           KA Jamieson  68c56d09               Delhi Capitals
38          PVD Chameera  327b58d3               Delhi Capitals
39             SU Parakh  926c7443               Delhi Capitals
40              MA Starc  3fb19989               Delhi Capitals
41              M Tiwari  fb5f69e4               Delhi Capitals
42               T Vijay  51ec3919               Delhi Capitals
43          Ashok Sharma  50c09020               Gujarat Titans
44       B Sai Sudharsan  d5130a30               Gujarat Titans
45           GD Phillips  9a46c4e5               Gujarat Titans
46            JC Buttler  99b75528               Gujarat Titans
47              K Rabada  e62dd25d               Gujarat Titans
48     M Prasidh Krishna  85e0cf10               Gujarat Titans
49       M Shahrukh Khan  7dcb9bc9               Gujarat Titans
50        Mohammed Siraj  2f49c897               Gujarat Titans
51             R Tewatia  39a2dfa8               Gujarat Titans
52           Rashid Khan  5f547c8b               Gujarat Titans
53          Shubman Gill  b4b99816               Gujarat Titans
54     Washington Sundar  f19ccfad               Gujarat Titans
55        Kumar Kushagra  57ca01b3               Gujarat Titans
56             JO Holder  0f721006               Gujarat Titans
57             MJ Suthar  025c4400               Gujarat Titans
58           Arshad Khan  12314277               Gujarat Titans
59              N Sindhu  3cea23da               Gujarat Titans
60         R Sai Kishore  c7a995d3               Gujarat Titans
61         A Raghuvanshi  d7017798        Kolkata Knight Riders
62             AM Rahane  29e95537        Kolkata Knight Riders
63                AS Roy  e4cdf230        Kolkata Knight Riders
64          B Muzarabani  449f4e3c        Kolkata Knight Riders
65               C Green  eaa76d3c        Kolkata Knight Riders
66              CV Varun  5b7ab5a9        Kolkata Knight Riders
67              FH Allen  bf74b130        Kolkata Knight Riders
68          Kartik Tyagi  5d2eea49        Kolkata Knight Riders
69             MK Pandey  93b4fc78        Kolkata Knight Riders
70              RK Singh  0a509d6b        Kolkata Knight Riders
71       Ramandeep Singh  be24ead0        Kolkata Knight Riders
72             SP Narine  9d430b40        Kolkata Knight Riders
73              VG Arora  7c3b3b78        Kolkata Knight Riders
74         Navdeep Saini  21d4e29b        Kolkata Knight Riders
75              R Powell  650d5e49        Kolkata Knight Riders
76            TL Seifert  4663bd23        Kolkata Knight Riders
77              SR Dubey  11061889        Kolkata Knight Riders
78           M Pathirana  64839cb3        Kolkata Knight Riders
79              T Dahiya  f12fe2a1        Kolkata Knight Riders
80              A Badoni  872b03f7         Lucknow Super Giants
81              A Nortje  acdc62f5         Lucknow Super Giants
82            AK Markram  6a26221c         Lucknow Super Giants
83           Abdul Samad  8e514b4c         Lucknow Super Giants
84          MD Choudhary  1c84109e         Lucknow Super Giants
85              MR Marsh  3d8feaf8         Lucknow Super Giants
86        Mohammed Shami  8cf9814c         Lucknow Super Giants
87           Mohsin Khan  c33d8116         Lucknow Super Giants
88              N Pooran  3241e3fd         Lucknow Super Giants
89          Prince Yadav  80b2fb19         Lucknow Super Giants
90               RR Pant  919a3be2         Lucknow Super Giants
91         Shahbaz Ahmed  f9e6e7ef         Lucknow Super Giants
92            Avesh Khan  eef2536f         Lucknow Super Giants
93              DS Rathi  13fc5c6d         Lucknow Super Giants
94           M Siddharth  cf0ccafa         Lucknow Super Giants
95              GF Linde  e5437608         Lucknow Super Giants
96          Himmat Singh  ebcfef83         Lucknow Super Giants
97              MP Yadav  b1ad996b         Lucknow Super Giants
98    Akshat Raghuwanshi  d8d67045         Lucknow Super Giants
99             JP Inglis  989889ff         Lucknow Super Giants
100          AA Kulkarni  2d140b79         Lucknow Super Giants
101          Akash Singh  b483905d         Lucknow Super Giants
102      Arjun Tendulkar  44aac2f0         Lucknow Super Giants
103         AM Ghazanfar  9ca68676               Mumbai Indians
104            HH Pandya  dbe50b21               Mumbai Indians
105            JJ Bumrah  462411b3               Mumbai Indians
106           M Markande  a9fd84fb               Mumbai Indians
107           Naman Dhir  fffa744b               Mumbai Indians
108         RD Rickelton  e66732f8               Mumbai Indians
109            RG Sharma  740742ef               Mumbai Indians
110             SA Yadav  271f83cd               Mumbai Indians
111        SE Rutherford  d014d5ac               Mumbai Indians
112            SN Thakur  1abb78f8               Mumbai Indians
113             TA Boult  a818c1be               Mumbai Indians
114          Tilak Varma  b0482a1d               Mumbai Indians
115              C Bosch  172dff15               Mumbai Indians
116            DL Chahar  23eeb873               Mumbai Indians
117           MJ Santner  e4a0deae               Mumbai Indians
118         Mayank Rawat  2b801189               Mumbai Indians
119            Q de Kock  372455c4               Mumbai Indians
120        Ashwani Kumar  d45c29b1               Mumbai Indians
121           DV Malewar  9e6032fa               Mumbai Indians
122         Krish Bhagat  e48a4814               Mumbai Indians
123              RA Bawa  ba6b2f91               Mumbai Indians
124               R Minz  bafd0398               Mumbai Indians
125             WG Jacks  9caf69a1               Mumbai Indians
126         Raghu Sharma  5b615e7c               Mumbai Indians
127       Arshdeep Singh  244048f6                 Punjab Kings
128           C Connolly  fe366f34                 Punjab Kings
129             M Jansen  81c36ee9                 Punjab Kings
130           MP Stoinis  d9273ee7                 Punjab Kings
131            N Wadhera  d1a60072                 Punjab Kings
132       P Simran Singh  9418198b                 Punjab Kings
133        Priyansh Arya  b5797845                 Punjab Kings
134              SS Iyer  85ec8e33                 Punjab Kings
135       Shashank Singh  26989d80                 Punjab Kings
136    Vijaykumar Vyshak  54e52590                 Punjab Kings
137          XC Bartlett  3b53243a                 Punjab Kings
138            YS Chahal  57ee1fde                 Punjab Kings
139        Harpreet Brar  c05edf8e                 Punjab Kings
140          LH Ferguson  2f9d0389                 Punjab Kings
141      Suryansh Shedge  970ddd24                 Punjab Kings
142         BJ Dwarshuis  e1b9f3a9                 Punjab Kings
143          Yash Thakur  4b31f3a3                 Punjab Kings
144   Azmatullah Omarzai  8f6dd463                 Punjab Kings
145         Vishnu Vinod  0494fa6e                 Punjab Kings
146       Brijesh Sharma  133bbd61             Rajasthan Royals
147          Dhruv Jurel  bcf325d2             Rajasthan Royals
148            JC Archer  5574750c             Rajasthan Royals
149             N Burger  465aa633             Rajasthan Royals
150              R Parag  04a418e8             Rajasthan Royals
151            RA Jadeja  fe93fd9d             Rajasthan Royals
152         Ravi Bishnoi  df064e1a             Rajasthan Royals
153           SO Hetmyer  48a1d7b7             Rajasthan Royals
154       Sandeep Sharma  ce820073             Rajasthan Royals
155        V Suryavanshi  470f446b             Rajasthan Royals
156          YBK Jaiswal  6c19c6e5             Rajasthan Royals
157           D Ferreira  f0af99a7             Rajasthan Royals
158         TU Deshpande  46a9bea1             Rajasthan Royals
159         LG Pretorius  60aa2db3             Rajasthan Royals
160       Yash Raj Punja  02dfebbe             Rajasthan Royals
161           Ravi Singh  548516a6             Rajasthan Royals
162             SB Dubey  6b2ff18f             Rajasthan Royals
163           MD Shanaka  3ff033bb             Rajasthan Royals
164             AF Milne  350bb1b1             Rajasthan Royals
165            SS Mishra  92500ad5             Rajasthan Royals
166     Abhinandan Singh  82c10dac  Royal Challengers Bengaluru
167              B Kumar  2e81a32d  Royal Challengers Bengaluru
168           D Padikkal  2c25d4f5  Royal Challengers Bengaluru
169             JA Duffy  dadbdb68  Royal Challengers Bengaluru
170            JM Sharma  800d2d97  Royal Challengers Bengaluru
171            KH Pandya  5b8c830e  Royal Challengers Bengaluru
172              PD Salt  3d284ca3  Royal Challengers Bengaluru
173           R Shepherd  c5aef772  Royal Challengers Bengaluru
174           RM Patidar  c740ea83  Royal Challengers Bengaluru
175        Suyash Sharma  9440ef41  Royal Challengers Bengaluru
176             TH David  f1f99156  Royal Challengers Bengaluru
177              V Kohli  ba607b88  Royal Challengers Bengaluru
178           JG Bethell  3c55c703  Royal Challengers Bengaluru
179         JR Hazlewood  03806cf8  Royal Challengers Bengaluru
180              VR Iyer  a24be938  Royal Challengers Bengaluru
181         Rasikh Salam  b8527c3d  Royal Challengers Bengaluru
182      Abhishek Sharma  f29185a1          Sunrisers Hyderabad
183         Aniket Verma  a3b0600d          Sunrisers Hyderabad
184             DA Payne  6c79c098          Sunrisers Hyderabad
185            E Malinga  5750bcb4          Sunrisers Hyderabad
186            H Klaasen  235c2bb6          Sunrisers Hyderabad
187             HV Patel  f986ca1a          Sunrisers Hyderabad
188          Harsh Dubey  25228673          Sunrisers Hyderabad
189         Ishan Kishan  752f7486          Sunrisers Hyderabad
190           JD Unadkat  1e66c162          Sunrisers Hyderabad
191  Nithish Kumar Reddy  aad0c365          Sunrisers Hyderabad
192              S Arora  d7423da1          Sunrisers Hyderabad
193              TM Head  12b610c2          Sunrisers Hyderabad
194        Shivang Kumar  7b44eb3e          Sunrisers Hyderabad
195       LS Livingstone  50c6bc2b          Sunrisers Hyderabad
196             PP Hinge  ece7b6b3          Sunrisers Hyderabad
197        Sakib Hussain  280fff14          Sunrisers Hyderabad
198         D Madushanka  de7d833e          Sunrisers Hyderabad
199           PJ Cummins  ded9240e          Sunrisers Hyderabad
200             R Smaran  c1e53c3f          Sunrisers Hyderabad

In [14]:
deliveries_df = load_delivery_files(IPL_DATA_FOLDER, reg_season_ids)
deliveries_df.info()

✓ Total deliveries loaded: 16,548
<class 'pandas.DataFrame'>
RangeIndex: 16548 entries, 0 to 16547
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         16548 non-null  int64
 1   team             16548 non-null  str
 2   over             16548 non-null  int64
 3   actual_delivery  16548 non-null  str
 4   batsman          16548 non-null  str
 5   bowler           16548 non-null  str
 6   non_striker      16548 non-null  str
 7   batter_runs      16548 non-null  int64
 8   extra_type       16548 non-null  str
 9   extra_runs       16548 non-null  int64
 10  total_runs       16548 non-null  int64
 11  review_by        16548 non-null  str
 12  review_umpire    16548 non-null  str
 13  review_batter    16548 non-null  str
 14  review_decision  16548 non-null  str
 15  review_type      16548 non-null  str
 16  player_out       16548 non-null  str
 17  wicket_fielder   16548 non-null  str
 18  wicket_kind      16548 non-null  str
 19  powerplay_flag   16548 non-null  int64
 20  powerplays_type  16548 non-null  str
dtypes: int64(6), str(15)
memory usage: 3.5 MB

In [46]:
def calculate_batting_stats(deliveries_df, players_df):
     """
    Calculates overall season batting stats for every player from the deliveries DataFrame.
    Returns a single player_stats_df with one row per player containing:
      - Batting stats
    All joined to the players table on player_name.

    Corrections applied:
      - Wides excluded from balls faced (no-balls count as faced)
      - Dismissals counted via player_dismissed (catches non-striker run outs too)
    """
     
      # -------------------------------------------------------
    # BATTING STATS
    # grouped by striker (the batter facing the ball)
    # -------------------------------------------------------

    # A ball counts as faced only if it's not a wide
    # No-balls count as faced — batter can play the ball
     deliveries_df["ball_faced"] = (deliveries_df["extra_type"] != "wides").astype(int)

    # Boundary fours and sixes
     deliveries_df["is_four"] = (deliveries_df["batter_runs"] == 4).astype(int)
     deliveries_df["is_six"]  = (deliveries_df["batter_runs"] == 6).astype(int)

     #Dot balls
     deliveries_df["is_dot_ball"] = (deliveries_df["total_runs"] == 0).astype(int)

     #Separate deliveries of innings into Powerplay, Middle Period and Death Overs
     

    # Assign clean flags that completely ignore individual wide/no-ball row counts
     deliveries_df["is_death"] = (
    (deliveries_df["over"] >= 15) & 
    (deliveries_df["powerplay_flag"] == 0)
     ).astype(int)

     deliveries_df["is_middle"] = (
    (deliveries_df["powerplay_flag"] == 0) & 
    (deliveries_df["is_death"] == 0)
     ).astype(int)

         

     ## ----------------------------------------------------
     ## POWERPLAY BATTING STATS
     ## ----------------------------------------------------
     pp_batting_stats = deliveries_df[deliveries_df["powerplay_flag"] == 1].groupby("batsman").agg(
          pp_runs      = ("batter_runs",     "sum"),
          pp_balls_faced = ("ball_faced",    "sum"),
          pp_dot_balls   = ("is_dot_ball",   "sum"),
          pp_fours       = ("is_four",       "sum"),
          pp_sixes       = ("is_six",        "sum"),
          pp_innings_batted = ("match_id",    "nunique")
     ).reset_index().rename(columns= {"batsman": "player_name"})

     ## ----------------------------------------------------
     ## MIDDLE OVERS BATTING STATS
     ## ----------------------------------------------------
     middle_batting_stats = deliveries_df[deliveries_df["is_middle"] == 1].groupby("batsman").agg(
          middle_runs          = ("batter_runs",     "sum"),
          middle_balls_faced   = ("ball_faced",      "sum"),
          middle_dot_balls     = ("is_dot_ball",     "sum"),
          middle_fours         = ("is_four",         "sum"),
          middle_sixes         = ("is_six",          "sum"),
          middle_innings_batted = ("match_id",       "nunique")
     ).reset_index().rename(columns={"batsman": "player_name"})
     
     ## ----------------------------------------------------
     ## DEATH OVERS BATTING STATS
     ## ----------------------------------------------------
     death_batting_stats = deliveries_df[deliveries_df["is_death"] == 1].groupby("batsman").agg(
          death_runs          = ("batter_runs",     "sum"),
          death_balls_faced   = ("ball_faced",      "sum"),
          death_dot_balls     = ("is_dot_ball",     "sum"),
          death_fours         = ("is_four",         "sum"),
          death_sixes         = ("is_six",          "sum"),
          death_innings_batted = ("match_id",       "nunique")
     ).reset_index().rename(columns={"batsman": "player_name"})

     ## -----------------------------------------------------
     ## INNINGS PERIOD BATTING STATS
     ## -----------------------------------------------------
     master_batting_df = pp_batting_stats.merge(middle_batting_stats, on="player_name", how="outer")
     master_batting_df = master_batting_df.merge(death_batting_stats, on="player_name", how="outer")
     master_batting_df.fillna(0, inplace=True)

     ## STRIKE RATE FOR EACH BATSMAN FOR EACH PHASE
     master_batting_df["pp_strike_rate"] = (master_batting_df["pp_runs"] / master_batting_df["pp_balls_faced"] * 100).fillna(0).round(2)
     master_batting_df["middle_strike_rate"] = (master_batting_df["middle_runs"] / master_batting_df["middle_balls_faced"] * 100).fillna(0).round(2)
     master_batting_df["death_strike_rate"] = (master_batting_df["death_runs"] / master_batting_df["death_balls_faced"] * 100).fillna(0).round(2)

     ## BATTING BOUNDARY PERCENTAGE FOR EACH BATSMAN EACH PHASE
     master_batting_df["pp_boundary_pct"] = ((master_batting_df["pp_fours"] + master_batting_df["pp_sixes"]) / master_batting_df["pp_balls_faced"] * 100).fillna(0).round(2)
     master_batting_df["middle_boundary_pct"] = ((master_batting_df["middle_fours"] + master_batting_df["middle_sixes"]) / master_batting_df["middle_balls_faced"] * 100).fillna(0).round(2)
     master_batting_df["death_boundary_pct"] = ((master_batting_df["death_fours"] + master_batting_df["death_sixes"]) / master_batting_df["death_balls_faced"] * 100).fillna(0).round(2)

     ## DOT BALL PERCENTAGE FOR EACH BATSMAN FOR EACH PHASE
     master_batting_df["pp_dot_ball_pct"] = (master_batting_df["pp_dot_balls"] / master_batting_df['pp_balls_faced'] *100).fillna(0).round(2)
     master_batting_df["middle_dot_ball_pct"] = (master_batting_df["middle_dot_balls"] / master_batting_df['middle_balls_faced'] *100).fillna(0).round(2)
     master_batting_df["death_dot_ball_pct"] = (master_batting_df["death_dot_balls"] / master_batting_df['death_balls_faced'] *100).fillna(0).round(2)

     
     #Non boundary Strike Rate - PowerPlay
     master_batting_df["pp_non_boundary_runs"] = (master_batting_df["pp_runs"] - ((4 * master_batting_df["pp_fours"]) + (6 * master_batting_df["pp_sixes"]))).fillna(0)
     master_batting_df["pp_non_boundary_balls"] =(master_batting_df["pp_balls_faced"] -(master_batting_df["pp_fours"] + master_batting_df["pp_sixes"])).fillna(0)
     master_batting_df["pp_non_boundary_strike_rate"] = (master_batting_df["pp_non_boundary_runs"] / master_batting_df["pp_non_boundary_balls"] * 100).fillna(0).round(2)

     #Non boundary Strike Rate - Middle Overs
     master_batting_df["middle_non_boundary_runs"] = (master_batting_df["middle_runs"] - ((4 * master_batting_df["middle_fours"]) + (6 * master_batting_df["middle_sixes"]))).fillna(0)
     master_batting_df["middle_non_boundary_balls"] =(master_batting_df["middle_balls_faced"] -(master_batting_df["middle_fours"] + master_batting_df["middle_sixes"])).fillna(0)
     master_batting_df["middle_non_boundary_strike_rate"] = (master_batting_df["middle_non_boundary_runs"] / master_batting_df["middle_non_boundary_balls"] *100).fillna(0).round(2)

     #Non boundary Strike Rate - Death Overs
     master_batting_df["death_non_boundary_runs"] = (master_batting_df["death_runs"] - ((4 * master_batting_df["death_fours"]) + (6 * master_batting_df["death_sixes"]))).fillna(0)
     master_batting_df["death_non_boundary_balls"] =(master_batting_df["death_balls_faced"] -(master_batting_df["death_fours"] + master_batting_df["death_sixes"])).fillna(0)
     master_batting_df["death_non_boundary_strike_rate"] = (master_batting_df["death_non_boundary_runs"] / master_batting_df["death_non_boundary_balls"] * 100).fillna(0).round(2)

     ## --------------------------------------------------
     ## OVERALL BATTING STATS
     ## ----------------------------------------------------
     batting_stats = deliveries_df.groupby("batsman").agg(
        runs           = ("batter_runs",  "sum"),
        balls_faced    = ("ball_faced",    "sum"),
        dot_balls      = ("is_dot_ball",   "sum"),
        fours          = ("is_four",       "sum"),
        sixes          = ("is_six",        "sum"),
        innings_batted = ("match_id",      "nunique")
    ).reset_index().rename(columns={"batsman": "player_name"})
     
     # Dismissals — grouped by player_dismissed so non-striker run outs are included
     dismissals = (deliveries_df[(deliveries_df["player_out"].notna()) & (deliveries_df["player_out"] != "")]
                    .groupby("player_out")
                    .size()
                    .reset_index())
     dismissals.columns = ["player_name", "dismissals"]

     batting_stats = batting_stats.merge(dismissals, on="player_name", how="left")
     batting_stats["dismissals"] = batting_stats["dismissals"].fillna(0).astype(int)

    # Strike rate = (runs / balls faced) * 100
     batting_stats["strike_rate"] = (
        batting_stats["runs"] / batting_stats["balls_faced"] * 100
    ).round(2)

    # Batting average = runs / dismissals (NaN if never dismissed)
     batting_stats["batting_average"] = (
        batting_stats["runs"] / batting_stats["dismissals"].replace(0, float("nan"))
    ).round(2)
     
    # Batting boundary percentage = (fours + sixes) / balls_faced * 100
     batting_stats["boundary_pct"] = ((batting_stats["fours"] + batting_stats["sixes"]) / batting_stats["balls_faced"] * 100).round(2)
     
     # Dot ball percentage
     batting_stats["dot_ball_pct"] = (batting_stats["dot_balls"] / batting_stats['balls_faced'] * 100).round(2)

     #Non boundary Strike Rate
     batting_stats["non_boundary_runs"] = (batting_stats["runs"] - ((4 * batting_stats["fours"]) + (6 * batting_stats["sixes"])))
     batting_stats["non_boundary_balls"] =(batting_stats["balls_faced"] -(batting_stats["fours"] + batting_stats["sixes"]))
     batting_stats["non_boundary_strike_rate"] = (batting_stats["non_boundary_runs"] / batting_stats["non_boundary_balls"] * 100).round(2)

     
     player_batting_stats_df = (players_df
        .merge(batting_stats,  on="player_name", how="left"))
     player_batting_stats_df = (player_batting_stats_df.merge(master_batting_df, on="player_name", how="outer"))
     
     print(f"✓ Player stats calculated: {len(player_batting_stats_df)} players")
     print(f"  Columns: {list(player_batting_stats_df.columns)}")

     return player_batting_stats_df

In [47]:
player_batting_stats_df = calculate_batting_stats(deliveries_df=deliveries_df, players_df=players_df)
player_batting_stats_df= player_batting_stats_df[(player_batting_stats_df["team"].notna())]
player_batting_stats_df

✓ Player stats calculated: 201 players
  Columns: ['player_name', 'id', 'team', 'runs', 'balls_faced', 'dot_balls', 'fours', 'sixes', 'innings_batted', 'dismissals', 'strike_rate', 'batting_average', 'boundary_pct', 'dot_ball_pct', 'non_boundary_runs', 'non_boundary_balls', 'non_boundary_strike_rate', 'pp_runs', 'pp_balls_faced', 'pp_dot_balls', 'pp_fours', 'pp_sixes', 'pp_innings_batted', 'middle_runs', 'middle_balls_faced', 'middle_dot_balls', 'middle_fours', 'middle_sixes', 'middle_innings_batted', 'death_runs', 'death_balls_faced', 'death_dot_balls', 'death_fours', 'death_sixes', 'death_innings_batted', 'pp_strike_rate', 'middle_strike_rate', 'death_strike_rate', 'pp_boundary_pct', 'middle_boundary_pct', 'death_boundary_pct', 'pp_dot_ball_pct', 'middle_dot_ball_pct', 'death_dot_ball_pct', 'pp_non_boundary_runs', 'pp_non_boundary_balls', 'pp_non_boundary_strike_rate', 'middle_non_boundary_runs', 'middle_non_boundary_balls', 'middle_non_boundary_strike_rate', 'death_non_boundary_runs', 'death_non_boundary_balls', 'death_non_boundary_strike_rate']

,player_name,id,team,runs,balls_faced,dot_balls,fours,sixes,innings_batted,dismissals,strike_rate,batting_average,boundary_pct,dot_ball_pct,non_boundary_runs,non_boundary_balls,non_boundary_strike_rate,pp_runs,pp_balls_faced,pp_dot_balls,pp_fours,pp_sixes,pp_innings_batted,middle_runs,middle_balls_faced,middle_dot_balls,middle_fours,middle_sixes,middle_innings_batted,death_runs,death_balls_faced,death_dot_balls,death_fours,death_sixes,death_innings_batted,pp_strike_rate,middle_strike_rate,death_strike_rate,pp_boundary_pct,middle_boundary_pct,death_boundary_pct,pp_dot_ball_pct,middle_dot_ball_pct,death_dot_ball_pct,pp_non_boundary_runs,pp_non_boundary_balls,pp_non_boundary_strike_rate,middle_non_boundary_runs,middle_non_boundary_balls,middle_non_boundary_strike_rate,death_non_boundary_runs,death_non_boundary_balls,death_non_boundary_strike_rate
0,A Badoni,872b03f7,Lucknow Super Giants,215.0,141.0,48.0,23.0,9.0,10.0,10.0,152.48,21.50,22.70,34.04,69.0,109.0,63.30,95.0,52.0,20.0,12.0,5.0,6.0,96.0,75.0,23.0,10.0,2.0,7.0,24.0,14.0,5.0,1.0,2.0,3.0,182.69,128.00,171.43,32.69,16.00,21.43,38.46,30.67,35.71,17.0,35.0,48.57,44.0,63.0,69.84,8.0,11.0,72.73
1,A Kamboj,fcc21ace,Chennai Super Kings,58.0,38.0,6.0,3.0,4.0,4.0,1.0,152.63,58.00,18.42,15.79,22.0,31.0,70.97,0.0,0.0,0.0,0.0,0.0,0.0,19.0,8.0,2.0,1.0,2.0,1.0,39.0,30.0,4.0,2.0,2.0,3.0,0.00,237.50,130.00,0.00,37.50,13.33,0.00,25.00,13.33,0.0,0.0,0.00,3.0,5.0,60.00,19.0,26.0,73.08
2,A Mhatre,b2b4f545,Chennai Super Kings,201.0,113.0,38.0,20.0,12.0,6.0,6.0,177.88,33.50,28.32,33.63,49.0,81.0,60.49,98.0,53.0,24.0,15.0,4.0,5.0,97.0,53.0,13.0,5.0,8.0,2.0,6.0,7.0,1.0,0.0,0.0,1.0,184.91,183.02,85.71,35.85,24.53,0.00,45.28,24.53,14.29,14.0,34.0,41.18,29.0,40.0,72.50,6.0,7.0,85.71
3,A Nortje,acdc62f5,Lucknow Super Giants,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.00,0.00,0.00,100.00,0.0,1.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,100.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,1.0,0.00
4,A Raghuvanshi,d7017798,Kolkata Knight Riders,422.0,288.0,93.0,40.0,19.0,12.0,10.0,146.53,42.20,20.49,32.29,148.0,229.0,64.63,129.0,102.0,48.0,12.0,7.0,11.0,214.0,146.0,39.0,20.0,8.0,8.0,79.0,40.0,6.0,8.0,4.0,4.0,126.47,146.58,197.50,18.63,19.18,30.00,47.06,26.71,15.00,39.0,83.0,46.99,86.0,118.0,72.88,23.0,28.0,82.14
5,AA Kulkarni,2d140b79,Lucknow Super Giants,17.0,25.0,14.0,1.0,0.0,2.0,2.0,68.00,8.50,4.00,56.00,13.0,24.0,54.17,8.0,13.0,8.0,0.0,0.0,2.0,9.0,12.0,6.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,61.54,75.00,0.00,0.00,8.33,0.00,61.54,50.00,0.00,8.0,13.0,61.54,5.0,11.0,45.45,0.0,0.0,0.00
6,AF Milne,350bb1b1,Rajasthan Royals,2.0,2.0,1.0,0.0,0.0,1.0,0.0,100.00,NaN,0.00,50.00,2.0,2.0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,1.0,0.00,0.00,100.00,0.00,0.00,0.00,0.00,0.00,50.00,0.0,0.0,0.00,0.0,0.0,0.00,2.0,2.0,100.00
7,AJ Hosein,4d7f517e,Chennai Super Kings,5.0,3.0,0.0,0.0,0.0,2.0,0.0,166.67,NaN,0.00,0.00,5.0,3.0,166.67,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,2.0,0.00,0.00,166.67,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,5.0,3.0,166.67
8,AK Markram,6a26221c,Lucknow Super Giants,231.0,167.0,52.0,20.0,11.0,11.0,9.0,138.32,25.67,18.56,31.14,85.0,136.0,62.50,120.0,87.0,35.0,13.0,6.0,7.0,57.0,52.0,12.0,3.0,1.0,6.0,54.0,28.0,5.0,4.0,4.0,3.0,137.93,109.62,192.86,21.84,7.69,28.57,40.23,23.08,17.86,32.0,68.0,47.06,39.0,48.0,81.25,14.0,20.0,70.00
9,AM Ghazanfar,9ca68676,Mumbai Indians,2.0,3.0,1.0,0.0,0.0,1.0,0.0,66.67,NaN,0.00,33.33,2.0,3.0,66.67,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,1.0,0.0,0.0,1.0,0.00,0.00,66.67,0.00,0.00,0.00,0.00,0.00,33.33,0.0,0.0,0.00,0.0,0.0,0.00,2.0,3.0,66.67
10,AM Rahane,29e95537,Kolkata Knight Riders,335.0,248.0,88.0,25.0,18.0,14.0,13.0,135.08,25.77,17.34,35.48,127.0,205.0,61.95,202.0,156.0,71.0,20.0,11.0,14.0,133.0,92.0,17.0,5.0,7.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,129.49,144.57,0.00,19.87,13.04,0.00,45.51,18.48,0.00,56.0,125.0,44.80,71.0,80.0,88.75,0.0,0.0,0.00
11,AR Patel,2e171977,Delhi Capitals,173.0,132.0,42.0,16.0,6.0,11.0,10.0,131.06,17.30,16.67,31.82,73.0,110.0,66.36,8.0,9.0,6.0,0.0,1.0,4.0,120.0,94.0,31.0,15.0,2.0,8.0,45.0,29.0,5.0,1.0,3.0,5.0,88.89,127.66,155.17,11.11,18.09,13.79,66.67,32.98,17.24,2.0,8.0,25.00,48.0,77.0,62.34,23.0,25.0,92.00
12,AS Roy,e4cdf230,Kolkata Knight Riders,52.0,39.0,12.0,3.0,2.0,7.0,4.0,133.33,13.00,12.82,30.77,28.0,34.0,82.35,0.0,0.0,0.0,0.0,0.0,0.0,15.0,17.0,7.0,1.0,0.0,5.0,37.0,22.0,5.0,2.0,2.0,4.0,0.00,88.24,168.18,0.00,5.88,18.18,0.00,41.18,22.73,0.0,0.0,0.00,11.0,16.0,68.75,17.0,18.0,94.44
13,Abdul Samad,8e514b4c,Lucknow Super Giants,116.0,88.0,31.0,10.0,5.0,7.0,6.0,131.82,19.33,17.05,35.23,46.0,73.0,63.01,0.0,0.0,0.0,0.0,0.0,0.0,62.0,55.0,22.0,5.0,2.0,7.0,54.0,33.0,9.0,5.0,3.0,4.0,0.00,112.73,163.64,0.00,12.73,24.24,0.00,40.00,27.27,0.0,0.0,0.00,30.0,48.0,62.50,16.0,25.0,64.00
14,Abhinandan Singh,82c10dac,Royal Challengers Bengaluru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Abhishek Sharma,f29185a1,Sunrisers Hyderabad,563.0,273.0,82.0,50.0,43.0,14.0,13.0,206.23,43.31,34.07,30.04,105.0,180.0,58.33,369.0,170.0,55.0,36.0,29.0,14.0,174.0,86.0,22.0,12.0,14.0,8.0,20.0,17.0,5.0,2.0,0.0,1.0,217.06,202.33,117.65,38.24,30.23,11.76,32.35,25.58,29.41,51.0,105.0,48.57,42.0,60.0,70.00,12.0,15.0,80.00
16,Abishek Porel,ad3b6e95,Delhi Capitals,108.0,88.0,34.0,15.0,1.0,4.0,4.0,122.73,27.00,18.18,38.64,42.0,72.0,58.33,66.0,51.0,24.0,11.0,1.0,4.0,38.0,34.0,8.0,3.0,0.0,2.0,4.0,3.0,2.0,1.0,0.0,1.0,129.41,111.76,133.33,23.53,8.82,33.33,47.06,23.53,66.67,16.0,39.0,41.03,26.0,31.0,83.87,0.0,2.0,0.00
17,Akash Singh,b483905d,Lucknow Super Giants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Akshat Raghuwanshi,d8d67045,Lucknow Super Giants,29.0,25.0,6.0,1.0,1.0,2.0,2.0,116.00,14.50,8.00,24.00,19.0,23.0,82.61,0.0,0.0,0.0,0.0,0.0,0.0,29.0,25.0,6.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,116.00,0.00,0.00,8.00,0.00,0.00,24.00,0.00,0.0,0.0,0.00,19.0,23.0,82.61,0.0,0.0,0.00
19,Aniket Verma,a3b0600d,Sunrisers Hyderabad,79.0,54.0,17.0,6.0,5.0,8.0,6.0,146.30,13.17,20.37,31.48,25.0,43.0,58.14,0.0,0.0,0.0,0.0,0.0,0.0,16.0,21.0,9.0,2.0,0.0,5.0,63.0,33.0,8.0,4.0,5.0,5.0,0.00,76.19,190.91,0.00,9.52,27.27,0.00,42.86,24.24,0.0,0.0,0.00,8.0,19.0,42.11,17.0,24.0,70.83
20,Arjun Tendulkar,44aac2f0,Lucknow Super Giants,5.0,5.0,1.0,0.0,0.0,1.0,0.0,100.00,NaN,0.00,20.00,5.0,5.0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,1.0,0.0,0.0,1.0,0.00,0.00,100.00,0.00,0.00,0.00,0.00,0.00,20.00,0.0,0.0,0.00,0.0,0.0,0.00,5.0,5.0,100.00
21,Arshad Khan,12314277,Gujarat Titans,8.0,5.0,1.0,1.0,0.0,1.0,0.0,160.00,NaN,20.00,20.00,4.0,4.0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,5.0,1.0,1.0,0.0,1.0,0.00,0.00,160.00,0.00,0.00,20.00,0.00,0.00,20.00,0.0,0.0,0.00,0.0,0.0,0.00,4.0,4.0,100.00
22,Arshdeep Singh,244048f6,Punjab Kings,1.0,1.0,0.0,0.0,0.0,1.0,0.0,100.00,NaN,0.00,0.00,1.0,1.0,100.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.00,0.00,100.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,1.0,1.0,100.00
23,Ashok Sharma,50c09020,Gujarat Titans,1.0,4.0,3.0,0.0,0.0,2.0,0.0,25.00,NaN,0.00,75.00,1.0,4.0,25.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,2.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.00,33.33,0.00,0.00,0.00,0.00,0.00,66.67,100.00,0.0,0.0,0.00,1.0,3.0,33.33,0.0,1.0,0.00
24,Ashutosh Sharma,84d9c311,Delhi Capitals,171.0,94.0,30.0,15.0,12.0,8.0,5.0,181.91,34.20,28.72,31.91,39.0,67.0,58.21,0.0,0.0,0.0,0.0,0.0,0.0,26.0,23.0,11.0,1.0,2.0,3.0,145.0,71.0,19.0,14.0,10.0,7.0,0.00,113.04,204.23,0.00,13.04,33.80,0.00,47.83,26.76,0.0,0.0,0.00,10.0,20.0,50.00,29.0,47.0,61.70
25,Ashwani Kumar,d45c29b1,Mumbai Indians,1.0,6.0,5.0,0.0,0.0,1.0,0.0,16.67,NaN,0.00,83.33,1.0,6.0,16.67,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6.0,5.0,0.0,0.0,1.0,0.00,0.00,16.67,0.00,0.00,0.00,0.00,0.00,83.33,0.0,0.0,0.00,0.0,0.0,0.00,1.0,6.0,16.67
26,Auqib Nabi,7c3c0337,Delhi Capitals,14.0,4.0,1.0,2.0,1.0,2.0,1.0,350.00,14.00,75.00,25.00,0.0,1.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,0.0,1.0,0.0,1.0,10.0,3.0,1.0,1.0,1.0,2.0,0.00,400.00,333.33,0.00,100.00,66.67,0.00,0.00,33.33,0.0,0.0,0.00,0.0,0.0,0.00,0.0,1.0,0.00
27,Avesh Khan,eef2536f,Lucknow Super Giants,6.0,6.0,3.0,1.0,0.0,3.0,1.0,100.00,6.00,16.67,50.00,2.0,5.0,40.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,3.0,1.0,0.0,3.0,0.00,0.00,100.00,0.00,0.00,16.67,0.00,0.00,50.00,0.0,0.0,0.00,0.0,0.0,0.00,2.0,5.0,40.00
28,Azmatullah Omarzai,8f6dd463,Punjab Kings,52.0,27.0,10.0,3.0,5.0,2.0,2.0,192.59,26.00,29.63,37.04,10.0,19.0,52.63,0.0,0.0,0.0,0.0,0.0,0.0,12.0,7.0,3.0,1.0,1.0,1.0,40.0,20.0,7.0,2.0,4.0,2.0,0.00,171.43,200.00,0.00,28.57,30.00,0.00,42.86,35.00,0.0,0.0,0.00,2.0,5.0,40.00,8.0,14.0,57.14
29,B Kumar,2e81a32d,Royal Challengers Bengaluru,34.0,26.0,10.0,3.0,1.0,4.0,0.0,130.77,NaN,15.38,38.46,16.0,22.0,72.73,0.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0,1.0,0.0,0.0,1.0,30.0,23.0,9.0,3.0,1.0,4.0,0.00,133.33,130.43,0.00,0.00,17.39,0.00,33.33,39.13,0.0,0.0,0.00,4.0,3.0,133.33,12.0,19.0,63.16
30,B Muzarabani,449f4e3c,Kolkata Knight Riders,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,B Sai Sudharsan,d5130a30,Gujarat Titans,638.0,404.0,121.0,62.0,29.0,14.0,13.0,157.92,49.08,22.52,29.95,216.0,313.0,69.01,291.0,205.0,86.0,40.0,9.0,14.0,271.0,164.0,27.0,18.0,13.0,7.0,76.0,35.0,8.0,4.0,7.0,5.0,141.95,165.24,217.14,23.90,18.90,31.43,41.95,16.46,22.86,77.0,156.0,49.36,121.0,133.0,90.98,18.0,24.0,75.00
32,BJ Dwarshuis,e1b9f3a9,Punjab Kings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Brijesh Sharma,133bbd61,Rajasthan Royals,2.0,4.0,2.0,0.0,0.0,2.0,0.0,50.00,NaN,0.00,50.00,2.0,4.0,50.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,0.0,2.0,0.00,0.00,50.00,0.00,0.00,0.00,0.00,0.00,50.00,0.0,0.0,0.00,0.0,0.0,0.00,2.0,4.0,50.00
34,C Bosch,172dff15,Mumbai Indians,50.0,31.0,9.0,5.0,2.0,4.0,1.0,161.29,50.00,22.58,29.03,18.0,24.0,75.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,31.0,9.0,5.0,2.0,4.0,0.00,0.00,161.29,0.00,0.00,22.58,0.00,0.00,29.03,0.0,0.0,0.00,0.0,0.0,0.00,18.0,24.0,75.00
35,C Connolly,fe366f34,Punjab Kings,491.0,301.0,106.0,43.0,32.0,13.0,11.0,163.12,44.64,24.92,35.22,127.0,226.0,56.19,137.0,103.0,54.0,18.0,7.0,10.0,260.0,161.0,48.0,17.0,18.0,10.0,94.0,37.0,4.0,8.0,7.0,3.0,133.01,161.49,254.05,24.27,21.74,40.54,52.43,29.81,10.81,23.0,78.0,29.49,84.0,126.0,66.67,20.0,22.0,90.91
36,C Green,eaa76d3c,Kolkata Knight Riders,322.0,221.0,65.0,22.0,17.0,14.0,10.0,145.70,32.20,17.65,29.41,132.0,182.0,72.53,61.0,51.0,19.0,5.0,2.0,9.0,200.0,128.0,33.0,12.0,12.0,10.0,61.0,42.0,13.0,5.0,3.0,4.0,119.61,156.25,145.24,13.73,18.75,19.05,37.25,25.78,30.95,29.0,44.0,65.91,80.0,104.0,76.92,23.0,34.0,67.65
37,CV Varun,5b7ab5a9,Kolkata Knight Riders,5.0,6.0,4.0,1.0,0.0,2.0,2.0,83.33,2.50,16.67,66.67,1.0,5.0,20.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,6.0,4.0,1.0,0.0,2.0,0.00,0.00,83.33,0.00,0.00,16.67,0.00,0.00,66.67,0.0,0.0,0.00,0.0,0.0,0.00,1.0,5.0,20.00
38,D Brevis,844e79d1,Chennai Super Kings,151.0,118.0,44.0,8.0,10.0,8.0,8.0,127.97,18.88,15.25,37.29,59.0,100.0,59.00,3.0,6.0,3.0,0.0,0.0,2.0,110.0,91.0,33.0,5.0,7.0,8.0,38.0,21.0,8.0,3.0,3.0,3.0,50.00,120.88,180.95,0.00,13.19,28.57,50.00,36.26,38.10,3.0,6.0,50.00,48.0,79.0,60.76,8.0,15.0,53.33
39,D Ferreira,f0af99a7,Rajasthan Royals,267.0,157.0,57.0,23.0,19.0,11.0,8.0,170.06,33.38,26.75,36.31,61.0,115.0,53.04,14.0,11.0,5.0,1.0,1.0,1.0,118.0,81.0,26.0,15.0,3.0,8.0,135.0,65.0,26.0,7.0,15.0,8.0,127.27,145.68,207.69,18.18,22.22,33.85,45.45,32.10,40.00,4.0,9.0,44.44,40.0,63.0,63.49,17.0,43.0,39.53
40,D Madushanka,de7d833e,Sunrisers Hyderabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,D Padikkal,2c25d4f5,Royal Challengers Bengaluru,433.0,252.0,72.0,44.0,24.0,13.0,12.0,171.83,36.08,26.98,28.57,113.0,184.0,61.41,216.0,122.0,41.0,24.0,13.0,13.0,217.0,130.0,31.0,20.0,11.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,177.05,166.92,0.00,30.33,23.85,0.00,33.61,23.85,0.00,42.0,85.0,49.41,71.0,99.0,71.72,0.0,0.0,0.00
42,DA Miller,d67d5f00,Delhi Capitals,211.0,137.0,43.0,15.0,14.0,10.0,6.0,154.01,35.17,21.17,31.39,67.0,108.0,62.04,4.0,8.0,5.0,0.0,0.0,1.0,79.0,68.0,22.0,7.0,2.0,7.0,128.0,61.0,16.0,8.0,12.0,7.0,50.00,116.18,209.84,0.00,13.24,32.79,62.50,32.35,26.23,4.0,8.0,50.00,39.0,59.0,66.10,24.0,41.0,58.54
43,DA Payne,6c79c098,Sunrisers Hyderabad,6.0,5.0,0.0,0.0,0.0,1.0,0.0,120.00,NaN,0.00,0.00,6.0,5.0,120.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,5.0,0.0,0.0,0.0,1.0,0.00,0.00,120.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.00,6.0,5.0,120.00
44,DL Chahar,23eeb873,Mumbai Indians,25.0,19.0,9.0,3.0,1.0,4.0,2.0,131.58,12.50,21.05,47.37,7.0,15.0,46.67,0.0,0.0,0.0,0.0,0.0,0.0,6.0,5.0,1.0,1.0,0.0,1.0,19.0,14.0,8.0,2.0,1.0,3.0,0.00,120.00,135.71,0.00,20.00,21.43,0.00,20.00,57.14,0.0,0.0,0.00,2.0,4.0,50.00,5.0,11.0,45.45
45,DS Rathi,13fc5c6d,Lucknow Super Giants,2.0,5.0,2.0,0.0,0.0,2.0,0.0,40.00,NaN,0.00,40.00,2.0,5.0,40.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0,0.0,0.0,2.0,0.00,0.00,40.00,0.00,0.00,0.00,0.00,0.00,40.00,0.0,0.0,0.00,0.0,0.0,0.00,2.0,5.0,40.00
46,DV Malewar,9e6032fa,Mumbai Indians,2.0,5.0,3.0,0.0,0.0,2.0,2.0,40.00,1.00,0.00,60.00,2.0,5.0,40.00,2.0,5.0,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.00,0.00,0.00,0.00,0.00,0.00,60.00,0.00,0.00,2.0,5.0,40.00,0.0,0.0,0.00,0.0,0.0,0.00
47,Dhruv Jurel,bcf325d2,Rajasthan Royals,458.0,306.0,95.0,41.0,21.0,14.0,12.0,149.67,38.17,20.26,31.05,168.0,244.0,68.85,119.0,71.0,32.0,13.0,8.0,9.0,264.0,185.0,52.0,27.0,8.0,12.0,75.0,50.0,11.0,1.0,5.0,4.0,167.61,142.70,150.00,29.58,18.92,12.00,45.07,28.11,22.00,19.0,50.0,38.00,108.0,150.0,72.00,41.0,44.0,93.18
48,E Malinga,5750bcb4,Sunrisers Hyderabad,2.0,9.0,6.0,0.0,0.0,2.0,0.0,22.22,NaN,0.00,66.67,2.0,9.0,22.22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,0.0,0.0,1.0,2.0,6.0,4.0,0.0,0.0,1.0,0.00,0.00,33.33,0.00,0.00,0.00,0.00,66.67,66.67,0.0,0.0,0.00,0.0,3.0,0.00,2.0,6.0,33.33
49,FH Allen,bf74b130,Kolkata Knight Riders,349.0,163.0,57.0,33.0,28.0,11.0,10.0,214.11,34.90,37.42,34.97,49.0,102.0,48.04,207.0,113.0,46.0,29.0,10.0,11.0,142.0,50.0,11.0,4.0,18.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,183.19,284.00,0.00,34.51,44.00,0.00,40.71,22.00,0.00,31.0,74.0,41.89,18.0,28.0,64.29,0.0,0.0,0.00
50,GD Phillips,9a46c4e5,Gujarat Titans,67.0,54.0,14.0,4.0,2.0,5.0,4.0,124.07,16.75,11.11,25.93,39.0,48.0,81.25,4.0,5.0,2.0,0.0,0.0,1.0,32.0,26.0,5.0,1.0,1.0,4.0,31.0,23.0,7.0,3.0,1.0,2.0,80.00,123.08,134.78,0.00,7.69,17.39,40.00,19.23,30.43,4.0,5.0,80.00,22.0,24.0,91.67,13.0,19.0,68.42
51,GF Linde,e5437608,Lucknow Super Giants,31.0,21.0,9.0,6.0,0.0,3.0,3.0,147.62,10.33,28.57,42.86,7.0,15.0,46.67,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,21.0,9.0,6.0,0.0,3.0,0.00,0.00,147.62,0.00,0.00,28.57,0.00,0.00,42.86,0.0,0.0,0.00,0.0,0.0,0.00,7.0,15.0,46.67
52,Gurjapneet Singh,cc61ee8f,Chennai Super Kings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,H Klaasen,235c2bb6,Sunrisers Hyderabad,606.0,380.0,96.0,46.0,30.0,14.0,12.0,159.47,50.50,20.00,25.26,242.0,304.0,79.61,10.0,14.0,9.0,1.0,0.0,3.0,411.0,262.0,64.0,35.0,18.0,13.0,185.0,104.0,23.0,10.0,12.0,10.0,71.43,156.87,177.88,7.14,20.23,21.15,64.29,24.43,22.12,6.0,13.0,46.15,163.0,209.0,77.99,73.0,82.0,89.02
54,HH Pandya,dbe50b21,Mumbai Indians,206.0,149.0,46.0,21.0,7.0,10.0,9.0,138.26,22.89,18.79,30.87,80.0,121.0,66.12,6.0,4.0,1.0,1.0,0.0,2.0,120.0,86.0,26.0,13.0,4.0,9.0,80.0,59.0,19.0,7.0,3.0,7.0,150.00,139.53,135.59,25.00,19.77,16.95,25.00,30.23,32.20,2.0,3.0,66.67,44.0,69.0,63.77,34.0,49.0,69.39
55,HV Patel,f986ca1a,Sunrisers Hyderabad,10.0,9.0,4.0,2.0,0.0,3.0,3.0,111.11,3.33,22.22,44.44,2.0,7.0,28.57,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,9.0,4.0,2.0,0.0,3.0,0.00,0.00,111.11,0.00,0.00,22.22,0.00,0.00,44.44,0.0,0.0,0.00,0.0,0.0,0.00,2.0,7.0,28.57
56,Harpreet Brar,c05edf8e,Punjab Kings,5.0,3.0,1.0,1.0,0.0,1.0,0.0,166.67,NaN,33.33,33.33,1.0,2.0,50.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,3.0,1.0,1.0,0.0,1.0,0.00,0.00,166.67,0.00,0.00,33.33,0.00,0.00,33.33,0.0,0.0,0.00,0.0,0.0,0.00,1.0,2.0,50.00
57,Harsh Dubey,25228673,Sunrisers Hyderabad,13.0,9.0,3.0,2.0,0.0,4.0,2.0,144.44,6.50,22.22,33.33,5.0,7.0,71.43,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,9.0,3.0,2.0,0.0,4.0,0.00,0.00,144.44,0.00,0.00,22.22,0.00,0.00,33.33,0.0,0.0,0.00,0.0,0.0,0.00,5.0,7.0,71.43
58,Himmat Singh,ebcfef83,Lucknow Super Giants,92.0,69.0,19.0,5.0,5.0,5.0,3.0,133.33,30.67,14.49,27.54,42.0,59.0,71.19,0.0,0.0,0.0,0.0,0.0,0.0,27.0,30.0,11.0,0.0,2.0,3.0,65.0,39.0,8.0,5.0,3.0,4.0,0.00,90.00,166.67,0.00,6.67,20.51,0.00,36.67,20.51,0.0,0.0,0.00,15.0,28.0,53.57,27.0,31.0,87.10
59,Ishan Kishan,752f7486,Sunrisers Hyderabad,569.0,319.0,83.0,57.0,29.0,14.0,14.0,178.37,40.64,26.96,26.02,167.0,233.0,71.67,154.0,93.0,40.0,18.0,9.0,11.0,353.0,194.0,34.0,33.0,16.0,11.0,62.0,32.0,9.0,6.0,4.0,4.0,165.59,181.96,193.75,29.03,25.26,31.25,43.01,17.53,28.12,28.0,66.0,42.42,125.0,145.0,86.21,14.0,22.0,63.64
60,J Overton,59559bc2,Chennai Super Kings,136.0,86.0,23.0,13.0,6.0,6.0,5.0,158.14,27.20,22.09,26.74,48.0,67.0,71.64,0.0,0.0,0.0,0.0,0.0,0.0,47.0,30.0,7.0,2.0,3.0,2.0,89.0,56.0,16.0,11.0,3.0,6.0,0.00,156.67,158.93,0.00,16.67,25.00,0.00,23.33,28.57,0.0,0.0,0.00,21.0,25.0,84.00,27.0,42.0,64.29
61,JA Duffy,dadbdb68,Royal Challengers Bengaluru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,JC Archer,5574750c,Rajasthan Royals,53.0,38.0,11.0,3.0,3.0,8.0,4.0,139.47,13.25,15.79,28.95,23.0,32.0,71.88,0.0,0.0,0.0,0.0,0.0,0.0,8.0,11.0,6.0,1.0,0.0,2.0,45.0,27.0,5.0,2.0,3.0,7.0,0.00,72.73,166.67,0.00,9.09,18.52,0.00,54.55,18.52,0.0,0.0,0.00,4.0,10.0,40.00,19.0,22.0,86.36
63,JC Buttler,99b75528,Gujarat Titans,469.0,302.0,97.0,46.0,24.0,14.0,12.0,155.30,39.08,23.18,32.12,141.0,232.0,60.78,133.0,87.0,40.0,12.0,10.0,9.0,264.0,175.0,48.0,27.0,10.0,12.0,72.0,40.0,9.0,7.0,4.0,6.0,152.87,150.86,180.00,25.29,21.14,27.50,45.98,27.43,22.50,25.0,65.0,38.46,96.0,138.0,69.57,20.0,29.0,68.97
64,JD Unadkat,1e66c162,Sunrisers Hyderabad,4.0,3.0,1.0,0.0,0.0,1.0,0.0,133.33,NaN,0.00,33.33,4.0,3.0,133.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0,1.0,0.0,0.0,1.0,0.00,0.00,133.33,0.00,0.00,0.00,0.00,0.00,33.33,0.0,0.0,0.00,0.0,0.0,0.00,4.0,3.0,133.33
65,JG Bethell,3c55c703,Royal Challengers Bengaluru,96.0,77.0,28.0,12.0,3.0,7.0,7.0,124.68,13.71,19.48,36.36,30.0,62.0,48.39,83.0,61.0,25.0,12.0,3.0,7.0,13.0,16.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,136.07,81.25,0.00,24.59,0.00,0.00,40.98,18.75,0.00,17.0,46.0,36.96,13.0,16.0,81.25,0.0,0.0,0.00
66,JJ Bumrah,462411b3,Mumbai Indians,7.0,7.0,3.0,1.0,0.0,2.0,1.0,100.00,7.00,14.29,42.86,3.0,6.0,50.00,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2.0,0.0,1.0,0.0,1.0,2.0,5.0,3.0,0.0,0.0,1.0,0.00,250.00,40.00,0.00,50.00,0.00,0.00,0.00,60.00,0.0,0.0,0.00,1.0,1.0,100.00,2.0,5.0,40.00

In [48]:
player_batting_stats_df[player_batting_stats_df["player_name"].str.contains("Suryavanshi")]

,player_name,id,team,runs,balls_faced,dot_balls,fours,sixes,innings_batted,dismissals,strike_rate,batting_average,boundary_pct,dot_ball_pct,non_boundary_runs,non_boundary_balls,non_boundary_strike_rate,pp_runs,pp_balls_faced,pp_dot_balls,pp_fours,pp_sixes,pp_innings_batted,middle_runs,middle_balls_faced,middle_dot_balls,middle_fours,middle_sixes,middle_innings_batted,death_runs,death_balls_faced,death_dot_balls,death_fours,death_sixes,death_innings_batted,pp_strike_rate,middle_strike_rate,death_strike_rate,pp_boundary_pct,middle_boundary_pct,death_boundary_pct,pp_dot_ball_pct,middle_dot_ball_pct,death_dot_ball_pct,pp_non_boundary_runs,pp_non_boundary_balls,pp_non_boundary_strike_rate,middle_non_boundary_runs,middle_non_boundary_balls,middle_non_boundary_strike_rate,death_non_boundary_runs,death_non_boundary_balls,death_non_boundary_strike_rate
189,V Suryavanshi,470f446b,Rajasthan Royals,583.0,251.0,86.0,50.0,53.0,14.0,14.0,232.27,41.64,41.04,34.26,65.0,148.0,43.92,404.0,177.0,66.0,40.0,34.0,14.0,179.0,74.0,20.0,10.0,19.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,228.25,241.89,0.0,41.81,39.19,0.0,37.29,27.03,0.0,40.0,103.0,38.83,25.0,45.0,55.56,0.0,0.0,0.0

In [49]:
player_batting_stats_df[player_batting_stats_df["player_name"].str.contains("Pooran")]

,player_name,id,team,runs,balls_faced,dot_balls,fours,sixes,innings_batted,dismissals,strike_rate,batting_average,boundary_pct,dot_ball_pct,non_boundary_runs,non_boundary_balls,non_boundary_strike_rate,pp_runs,pp_balls_faced,pp_dot_balls,pp_fours,pp_sixes,pp_innings_batted,middle_runs,middle_balls_faced,middle_dot_balls,middle_fours,middle_sixes,middle_innings_batted,death_runs,death_balls_faced,death_dot_balls,death_fours,death_sixes,death_innings_batted,pp_strike_rate,middle_strike_rate,death_strike_rate,pp_boundary_pct,middle_boundary_pct,death_boundary_pct,pp_dot_ball_pct,middle_dot_ball_pct,death_dot_ball_pct,pp_non_boundary_runs,pp_non_boundary_balls,pp_non_boundary_strike_rate,middle_non_boundary_runs,middle_non_boundary_balls,middle_non_boundary_strike_rate,death_non_boundary_runs,death_non_boundary_balls,death_non_boundary_strike_rate
111,N Pooran,3241e3fd,Lucknow Super Giants,234.0,183.0,81.0,11.0,19.0,14.0,13.0,127.87,18.0,16.39,44.26,76.0,153.0,49.67,49.0,37.0,19.0,2.0,5.0,5.0,144.0,131.0,59.0,8.0,9.0,13.0,41.0,15.0,3.0,1.0,5.0,2.0,132.43,109.92,273.33,18.92,12.98,40.0,51.35,45.04,20.0,11.0,30.0,36.67,58.0,114.0,50.88,7.0,9.0,77.78

In [50]:
deliveries_df["wicket_kind"].unique()

<ArrowStringArray>
[                     '',                'caught',               'run out',
                'bowled',                   'lbw',     'caught and bowled',
               'stumped',           'retired out',          'retired hurt',
 'obstructing the field']
Length: 10, dtype: str

In [51]:
def calculate_bowling_stats(deliveries_df, players_df):
    """
    Calculates overall season bowling stats for every player from the deliveries DataFrame.
    Returns a single player_stats_df with one row per player containing:
      - Bowling stats
    All joined to the players table on player_name.

    Corrections applied:
      - Runs conceded includes wides and no-balls (but not byes or leg byes)
    """

    # -------------------------------------------------------
    # BOWLING STATS
    # grouped by bowler
    # -------------------------------------------------------

    # A legal delivery excludes wides and no-balls
    deliveries_df["is_legal"] = (
        (deliveries_df["extra_type"] != "wides") & (deliveries_df["extra_type"] != "noballs")
    ).astype(int)

    deliveries_df["wides"] = np.where(deliveries_df["extra_type"] == "wides", deliveries_df["extra_runs"], 0)
    deliveries_df["noballs"] = np.where(deliveries_df["extra_type"] == "noballs", deliveries_df["extra_runs"], 0)

    # Runs conceded by bowler = runs off bat + wides + no-balls
    # Byes and leg byes are NOT the bowler's fault
    deliveries_df["runs_conceded"] = (
        deliveries_df["batter_runs"].fillna(0) +
        deliveries_df["wides"].fillna(0) +
        deliveries_df["noballs"].fillna(0)
    )

     # Wickets credited to bowler — excludes run outs, retired hurt, obstructions
    deliveries_df["bowler_wicket"] = (
        deliveries_df["wicket_kind"].notna() &
        ~deliveries_df["wicket_kind"].isin([
            "run out", "retired hurt", "retired out", "obstructing the field", ""
        ])
    ).astype(int)

    # Dot balls = legal delivery where total runs == 0
    deliveries_df["is_dot"] = (
        (deliveries_df["is_legal"] == 1) & (deliveries_df["total_runs"] == 0)
    ).astype(int)

    # Boundaries balls = delivery where runs off bat == 4 OR 6
    deliveries_df["is_boundary"] = (
        (deliveries_df["batter_runs"].isin([4, 6]))
    ).astype(int)

    bowling_stats = deliveries_df.groupby("bowler").agg(
        balls_bowled   = ("is_legal",        "sum"),
        runs_conceded  = ("runs_conceded",    "sum"),
        wickets        = ("bowler_wicket",    "sum"),
        dot_balls      = ("is_dot",           "sum"),
        boundaries     = ("is_boundary",      "sum"),
        innings_bowled = ("match_id",         "nunique")
    ).reset_index().rename(columns={"bowler": "player_name"})

    # Overs bowled (balls / 6, rounded to 1 decimal)
    bowling_stats["over"], bowling_stats["ball"] = bowling_stats["balls_bowled"].divmod(6)
    bowling_stats["overs_bowled"] = (bowling_stats["over"].astype(int).astype(str) + '.' + bowling_stats["ball"].astype(int).astype(str)).astype(float)

    # Economy rate = runs conceded per over
    bowling_stats["economy"] = (
        bowling_stats["runs_conceded"] / bowling_stats["balls_bowled"] * 6
    ).round(2)

    # Bowling average = runs conceded per wicket
    bowling_stats["bowling_average"] = (
        bowling_stats["runs_conceded"] / bowling_stats["wickets"].replace(0, float("nan"))
    ).round(2)

    # Bowling strike rate = balls bowled per wicket
    bowling_stats["bowling_strike_rate"] = (
    bowling_stats["balls_bowled"] / bowling_stats["wickets"].replace(0, float("nan"))
    ).round(2)

    # Boundary percentage = legal deliveries hit for 4 or 6
    bowling_stats["boundary_pct"] = (bowling_stats["boundaries"] / bowling_stats["balls_bowled"] * 100).round(2)

    # Balls per boundary  = (Boundary percentage/100)^(-1)
    bowling_stats["balls_per_boundary"] = (100 / bowling_stats["boundary_pct"]).astype(int)    

    #Separate deliveries of innings into Powerplay, Middle Period and Death Overs
    # Assign clean flags that completely ignore individual wide/no-ball row counts
    deliveries_df["is_death"] = (
    (deliveries_df["over"] >= 15) & 
    (deliveries_df["powerplay_flag"] == 0)
     ).astype(int)

    deliveries_df["is_middle"] = (
    (deliveries_df["powerplay_flag"] == 0) & 
    (deliveries_df["is_death"] == 0)
     ).astype(int)


    ## ----------------------------------------------------
    ## POWERPLAY BOWLING STATS
    ## ----------------------------------------------------
    pp_bowling_stats = deliveries_df[deliveries_df["powerplay_flag"] == 1].groupby("bowler").agg(
        pp_balls_bowled   = ("is_legal",        "sum"),
        pp_runs_conceded  = ("runs_conceded",    "sum"),
        pp_wickets        = ("bowler_wicket",    "sum"),
        pp_dot_balls      = ("is_dot",           "sum"),
        pp_boundaries     = ("is_boundary",      "sum"),
        pp_innings_bowled = ("match_id",         "nunique")
    ).reset_index().rename(columns={"bowler": "player_name"})

    # Overs bowled (balls / 6, rounded to 1 decimal) - Powerplay
    pp_bowling_stats["pp_over"], pp_bowling_stats["pp_ball"] = pp_bowling_stats["pp_balls_bowled"].divmod(6)
    pp_bowling_stats["pp_overs_bowled"] = (pp_bowling_stats["pp_over"].astype(int).astype(str) + '.' + pp_bowling_stats["pp_ball"].astype(int).astype(str)).astype(float)

    # Economy rate = runs conceded per over - Powerplay
    pp_bowling_stats["pp_economy"] = (
        pp_bowling_stats["pp_runs_conceded"] / pp_bowling_stats["pp_balls_bowled"] * 6
    ).round(2)

    # Bowling average = runs conceded per wicket - Powerplay
    pp_bowling_stats["pp_bowling_average"] = (
        pp_bowling_stats["pp_runs_conceded"] / pp_bowling_stats["pp_wickets"].replace(0, float("nan"))
    ).round(2)

    # Bowling strike rate = balls bowled per wicket - Powerplay
    pp_bowling_stats["pp_bowling_strike_rate"] = (
    pp_bowling_stats["pp_balls_bowled"] / pp_bowling_stats["pp_wickets"].replace(0, float("nan"))
    ).round(2)

     # Boundary percentage = legal deliveries hit for 4 or 6
    pp_bowling_stats["pp_boundary_pct"] = (pp_bowling_stats["pp_boundaries"] / pp_bowling_stats["pp_balls_bowled"] * 100).fillna(0).round(2)

    # Balls per boundary  = (Boundary percentage/100)^(-1)
    pp_bowling_stats["pp_balls_per_boundary"] = (
    (pp_bowling_stats["pp_balls_bowled"] / pp_bowling_stats["pp_boundaries"])
    .replace([float('inf'), float('-inf')], 0)
    .astype(int)
)

    ## ----------------------------------------------------
    ## MIDDLE PERIOD BOWLING STATS
    ## ----------------------------------------------------
    middle_bowling_stats = deliveries_df[deliveries_df["is_middle"] == 1].groupby("bowler").agg(
        middle_balls_bowled   = ("is_legal",        "sum"),
        middle_runs_conceded  = ("runs_conceded",    "sum"),
        middle_wickets        = ("bowler_wicket",    "sum"),
        middle_dot_balls      = ("is_dot",           "sum"),
        middle_boundaries     = ("is_boundary",      "sum"),
        middle_innings_bowled = ("match_id",         "nunique")
    ).reset_index().rename(columns={"bowler": "player_name"})

    # Overs bowled (balls / 6, rounded to 1 decimal) - Middle Overs
    middle_bowling_stats["middle_over"], middle_bowling_stats["middle_ball"] = middle_bowling_stats["middle_balls_bowled"].divmod(6)
    middle_bowling_stats["middle_overs_bowled"] = (middle_bowling_stats["middle_over"].astype(int).astype(str) + '.' + middle_bowling_stats["middle_ball"].astype(int).astype(str)).astype(float)

    # Economy rate = runs conceded per over - Middle Overs
    middle_bowling_stats["middle_economy"] = (
        middle_bowling_stats["middle_runs_conceded"] / middle_bowling_stats["middle_balls_bowled"] * 6
    ).round(2)

    # Bowling average = runs conceded per wicket - Middle Overs
    middle_bowling_stats["middle_bowling_average"] = (
        middle_bowling_stats["middle_runs_conceded"] / middle_bowling_stats["middle_wickets"].replace(0, float("nan"))
    ).round(2)

    # Bowling strike rate = balls bowled per wicket - Middle Overs
    middle_bowling_stats["middle_bowling_strike_rate"] = (
    middle_bowling_stats["middle_balls_bowled"] / middle_bowling_stats["middle_wickets"].replace(0, float("nan"))
    ).round(2)

     # Boundary percentage = legal deliveries hit for 4 or 6
    middle_bowling_stats["middle_boundary_pct"] = (middle_bowling_stats["middle_boundaries"] / middle_bowling_stats["middle_balls_bowled"] * 100).fillna(0).round(2)

    # Balls per boundary  = (Boundary percentage/100)^(-1)
    middle_bowling_stats["middle_balls_per_boundary"] = (
    (middle_bowling_stats["middle_balls_bowled"] / middle_bowling_stats["middle_boundaries"])
    .replace([float('inf'), float('-inf')], 0)
    .astype(int)
)

    ## ----------------------------------------------------
    ## DEATH PERIOD BOWLING STATS
    ## ----------------------------------------------------
    death_bowling_stats = deliveries_df[deliveries_df["is_death"] == 1].groupby("bowler").agg(
        death_balls_bowled   = ("is_legal",        "sum"),
        death_runs_conceded  = ("runs_conceded",    "sum"),
        death_wickets        = ("bowler_wicket",    "sum"),
        death_dot_balls      = ("is_dot",           "sum"),
        death_boundaries     = ("is_boundary",      "sum"),
        death_innings_bowled = ("match_id",         "nunique")
    ).reset_index().rename(columns={"bowler": "player_name"})

    # Overs bowled (balls / 6, rounded to 1 decimal) - Death Overs
    death_bowling_stats["death_over"], death_bowling_stats["death_ball"] = death_bowling_stats["death_balls_bowled"].divmod(6)
    death_bowling_stats["death_overs_bowled"] = (death_bowling_stats["death_over"].astype(int).astype(str) + '.' + death_bowling_stats["death_ball"].astype(int).astype(str)).astype(float)

    # Economy rate = runs conceded per over -  Death Overs
    death_bowling_stats["death_economy"] = (
        death_bowling_stats["death_runs_conceded"] / death_bowling_stats["death_balls_bowled"] * 6
    ).round(2)

    # Bowling average = runs conceded per wicket - Death Overs
    death_bowling_stats["death_bowling_average"] = (
        death_bowling_stats["death_runs_conceded"] / death_bowling_stats["death_wickets"].replace(0, float("nan"))
    ).round(2)

    # Bowling strike rate = balls bowled per wicket - Death Overs
    death_bowling_stats["death_bowling_strike_rate"] = (
    death_bowling_stats["death_balls_bowled"] / death_bowling_stats["death_wickets"].replace(0, float("nan"))
    ).round(2)

     # Boundary percentage = legal deliveries hit for 4 or 6
    death_bowling_stats["death_boundary_pct"] = (death_bowling_stats["death_boundaries"] / death_bowling_stats["death_balls_bowled"] * 100).fillna(0).round(2)

    # Balls per boundary  = (Boundary percentage/100)^(-1)
    death_bowling_stats["death_balls_per_boundary"] = (
    (death_bowling_stats["death_balls_bowled"] / death_bowling_stats["death_boundaries"])
    .replace([float('inf'), float('-inf')], 0)
    .astype(int)
)
    
    player_bowling_stats_df = (players_df
        .merge(bowling_stats,  on="player_name", how="left"))

    master_bowling_df = pp_bowling_stats.merge(middle_bowling_stats, on="player_name", how="outer")
    master_bowling_df = master_bowling_df.merge(death_bowling_stats, on="player_name", how="outer")
    master_bowling_df.fillna(0, inplace=True)

    player_bowling_stats_df = (player_bowling_stats_df.merge(master_bowling_df, on="player_name", how="outer"))
     
    print(f"✓ Player stats calculated: {len(player_bowling_stats_df)} players")
    print(f"  Columns: {list(player_bowling_stats_df.columns)}")

    return player_bowling_stats_df

In [52]:
player_bowling_stats_df = calculate_bowling_stats(deliveries_df=deliveries_df, players_df=players_df)
player_bowling_stats_df= player_bowling_stats_df[(player_bowling_stats_df["team"].notna())]
player_bowling_stats_df

✓ Player stats calculated: 201 players
  Columns: ['player_name', 'id', 'team', 'balls_bowled', 'runs_conceded', 'wickets', 'dot_balls', 'boundaries', 'innings_bowled', 'over', 'ball', 'overs_bowled', 'economy', 'bowling_average', 'bowling_strike_rate', 'boundary_pct', 'balls_per_boundary', 'pp_balls_bowled', 'pp_runs_conceded', 'pp_wickets', 'pp_dot_balls', 'pp_boundaries', 'pp_innings_bowled', 'pp_over', 'pp_ball', 'pp_overs_bowled', 'pp_economy', 'pp_bowling_average', 'pp_bowling_strike_rate', 'pp_boundary_pct', 'pp_balls_per_boundary', 'middle_balls_bowled', 'middle_runs_conceded', 'middle_wickets', 'middle_dot_balls', 'middle_boundaries', 'middle_innings_bowled', 'middle_over', 'middle_ball', 'middle_overs_bowled', 'middle_economy', 'middle_bowling_average', 'middle_bowling_strike_rate', 'middle_boundary_pct', 'middle_balls_per_boundary', 'death_balls_bowled', 'death_runs_conceded', 'death_wickets', 'death_dot_balls', 'death_boundaries', 'death_innings_bowled', 'death_over', 'death_ball', 'death_overs_bowled', 'death_economy', 'death_bowling_average', 'death_bowling_strike_rate', 'death_boundary_pct', 'death_balls_per_boundary']

,player_name,id,team,balls_bowled,runs_conceded,wickets,dot_balls,boundaries,innings_bowled,over,ball,overs_bowled,economy,bowling_average,bowling_strike_rate,boundary_pct,balls_per_boundary,pp_balls_bowled,pp_runs_conceded,pp_wickets,pp_dot_balls,pp_boundaries,pp_innings_bowled,pp_over,pp_ball,pp_overs_bowled,pp_economy,pp_bowling_average,pp_bowling_strike_rate,pp_boundary_pct,pp_balls_per_boundary,middle_balls_bowled,middle_runs_conceded,middle_wickets,middle_dot_balls,middle_boundaries,middle_innings_bowled,middle_over,middle_ball,middle_overs_bowled,middle_economy,middle_bowling_average,middle_bowling_strike_rate,middle_boundary_pct,middle_balls_per_boundary,death_balls_bowled,death_runs_conceded,death_wickets,death_dot_balls,death_boundaries,death_innings_bowled,death_over,death_ball,death_overs_bowled,death_economy,death_bowling_average,death_bowling_strike_rate,death_boundary_pct,death_balls_per_boundary
0,A Badoni,872b03f7,Lucknow Super Giants,6.0,14.0,0.0,0.0,2.0,1.0,1.0,0.0,1.0,14.00,NaN,NaN,33.33,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,6.0,14.0,0.0,0.0,2.0,1.0,1.0,0.0,1.0,14.00,0.00,0.00,33.33,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
1,A Kamboj,fcc21ace,Chennai Super Kings,302.0,530.0,21.0,112.0,83.0,14.0,50.0,2.0,50.2,10.53,25.24,14.38,27.48,3.0,126.0,218.0,5.0,53.0,37.0,14.0,21.0,0.0,21.0,10.38,43.60,25.20,29.37,3.0,48.0,77.0,3.0,16.0,11.0,7.0,8.0,0.0,8.0,9.62,25.67,16.00,22.92,4.0,128.0,235.0,13.0,43.0,35.0,12.0,21.0,2.0,21.2,11.02,18.08,9.85,27.34,3.0
2,A Mhatre,b2b4f545,Chennai Super Kings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A Nortje,acdc62f5,Lucknow Super Giants,24.0,39.0,0.0,7.0,3.0,1.0,4.0,0.0,4.0,9.75,NaN,NaN,12.50,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,18.0,26.0,0.0,4.0,2.0,1.0,3.0,0.0,3.0,8.67,0.00,0.00,11.11,9.0,6.0,13.0,0.0,3.0,1.0,1.0,1.0,0.0,1.0,13.00,0.00,0.00,16.67,6.0
4,A Raghuvanshi,d7017798,Kolkata Knight Riders,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,AA Kulkarni,2d140b79,Lucknow Super Giants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,AF Milne,350bb1b1,Rajasthan Royals,20.0,41.0,0.0,2.0,4.0,1.0,3.0,2.0,3.2,12.30,NaN,NaN,20.00,5.0,12.0,22.0,0.0,1.0,2.0,1.0,2.0,0.0,2.0,11.00,0.00,0.00,16.67,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,8.0,19.0,0.0,1.0,2.0,1.0,1.0,2.0,1.2,14.25,0.00,0.00,25.00,4.0
7,AJ Hosein,4d7f517e,Chennai Super Kings,148.0,198.0,8.0,58.0,25.0,7.0,24.0,4.0,24.4,8.03,24.75,18.50,16.89,5.0,66.0,93.0,3.0,37.0,17.0,6.0,11.0,0.0,11.0,8.45,31.00,22.00,25.76,3.0,72.0,91.0,4.0,18.0,7.0,6.0,12.0,0.0,12.0,7.58,22.75,18.00,9.72,10.0,10.0,14.0,1.0,3.0,1.0,2.0,1.0,4.0,1.4,8.40,14.00,10.00,10.00,10.0
8,AK Markram,6a26221c,Lucknow Super Giants,36.0,83.0,0.0,8.0,11.0,5.0,6.0,0.0,6.0,13.83,NaN,NaN,30.56,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,24.0,54.0,0.0,6.0,7.0,3.0,4.0,0.0,4.0,13.50,0.00,0.00,29.17,3.0,12.0,29.0,0.0,2.0,4.0,2.0,2.0,0.0,2.0,14.50,0.00,0.00,33.33,3.0
9,AM Ghazanfar,9ca68676,Mumbai Indians,233.0,389.0,15.0,69.0,53.0,11.0,38.0,5.0,38.5,10.02,25.93,15.53,22.75,4.0,54.0,99.0,6.0,22.0,17.0,7.0,9.0,0.0,9.0,11.00,16.50,9.00,31.48,3.0,144.0,216.0,5.0,32.0,23.0,11.0,24.0,0.0,24.0,9.00,43.20,28.80,15.97,6.0,35.0,74.0,4.0,15.0,13.0,6.0,5.0,5.0,5.5,12.69,18.50,8.75,37.14,2.0
10,AM Rahane,29e95537,Kolkata Knight Riders,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,AR Patel,2e171977,Delhi Capitals,264.0,360.0,11.0,80.0,41.0,13.0,44.0,0.0,44.0,8.18,32.73,24.00,15.53,6.0,84.0,121.0,2.0,30.0,16.0,10.0,14.0,0.0,14.0,8.64,60.50,42.00,19.05,5.0,168.0,232.0,8.0,45.0,25.0,12.0,28.0,0.0,28.0,8.29,29.00,21.00,14.88,6.0,12.0,7.0,1.0,5.0,0.0,2.0,2.0,0.0,2.0,3.50,7.00,12.00,0.00,0.0
12,AS Roy,e4cdf230,Kolkata Knight Riders,163.0,261.0,9.0,50.0,32.0,12.0,27.0,1.0,27.1,9.61,29.00,18.11,19.63,5.0,60.0,93.0,1.0,20.0,13.0,7.0,10.0,0.0,10.0,9.30,93.00,60.00,21.67,4.0,78.0,125.0,6.0,23.0,14.0,9.0,13.0,0.0,13.0,9.62,20.83,13.00,17.95,5.0,25.0,43.0,2.0,7.0,5.0,5.0,4.0,1.0,4.1,10.32,21.50,12.50,20.00,5.0
13,Abdul Samad,8e514b4c,Lucknow Super Giants,1.0,6.0,0.0,0.0,1.0,1.0,0.0,1.0,0.1,36.00,NaN,NaN,100.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,1.0,6.0,0.0,0.0,1.0,1.0,0.0,1.0,0.1,36.00,0.00,0.00,100.00,1.0
14,Abhinandan Singh,82c10dac,Royal Challengers Bengaluru,58.0,122.0,3.0,15.0,20.0,3.0,9.0,4.0,9.4,12.62,40.67,19.33,34.48,2.0,24.0,69.0,0.0,6.0,13.0,3.0,4.0,0.0,4.0,17.25,0.00,0.00,54.17,1.0,24.0,37.0,1.0,5.0,5.0,3.0,4.0,0.0,4.0,9.25,37.00,24.00,20.83,4.0,10.0,16.0,2.0,4.0,2.0,2.0,1.0,4.0,1.4,9.60,8.00,5.00,20.00,5.0
15,Abhishek Sharma,f29185a1,Sunrisers Hyderabad,29.0,49.0,0.0,6.0,7.0,4.0,4.0,5.0,4.5,10.14,NaN,NaN,24.14,4.0,18.0,29.0,0.0,5.0,4.0,2.0,3.0,0.0,3.0,9.67,0.00,0.00,22.22,4.0,6.0,13.0,0.0,0.0,2.0,1.0,1.0,0.0,1.0,13.00,0.00,0.00,33.33,3.0,5.0,7.0,0.0,1.0,1.0,1.0,0.0,5.0,0.5,8.40,0.00,0.00,20.00,5.0
16,Abishek Porel,ad3b6e95,Delhi Capitals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Akash Singh,b483905d,Lucknow Super Giants,42.0,80.0,4.0,18.0,13.0,2.0,7.0,0.0,7.0,11.43,20.00,10.50,30.95,3.0,24.0,39.0,2.0,11.0,6.0,2.0,4.0,0.0,4.0,9.75,19.50,12.00,25.00,4.0,18.0,41.0,2.0,7.0,7.0,2.0,3.0,0.0,3.0,13.67,20.50,9.00,38.89,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
18,Akshat Raghuwanshi,d8d67045,Lucknow Super Giants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Aniket Verma,a3b0600d,Sunrisers Hyderabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Arjun Tendulkar,44aac2f0,Lucknow Super Giants,24.0,36.0,1.0,6.0,5.0,1.0,4.0,0.0,4.0,9.00,36.00,24.00,20.83,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,18.0,31.0,1.0,5.0,5.0,1.0,3.0,0.0,3.0,10.33,31.00,18.00,27.78,3.0,6.0,5.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,5.00,0.00,0.00,0.00,0.0
21,Arshad Khan,12314277,Gujarat Titans,80.0,140.0,5.0,34.0,21.0,5.0,13.0,2.0,13.2,10.50,28.00,16.00,26.25,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,54.0,98.0,2.0,23.0,15.0,5.0,9.0,0.0,9.0,10.89,49.00,27.00,27.78,3.0,26.0,42.0,3.0,11.0,6.0,3.0,4.0,2.0,4.2,9.69,14.00,8.67,23.08,4.0
22,Arshdeep Singh,244048f6,Punjab Kings,318.0,541.0,14.0,108.0,80.0,14.0,53.0,0.0,53.0,10.21,38.64,22.71,25.16,3.0,168.0,260.0,7.0,70.0,39.0,14.0,28.0,0.0,28.0,9.29,37.14,24.00,23.21,4.0,72.0,128.0,3.0,15.0,18.0,12.0,12.0,0.0,12.0,10.67,42.67,24.00,25.00,4.0,78.0,153.0,4.0,23.0,23.0,12.0,13.0,0.0,13.0,11.77,38.25,19.50,29.49,3.0
23,Ashok Sharma,50c09020,Gujarat Titans,126.0,228.0,6.0,48.0,35.0,6.0,21.0,0.0,21.0,10.86,38.00,21.00,27.78,3.0,24.0,60.0,0.0,6.0,11.0,4.0,4.0,0.0,4.0,15.00,0.00,0.00,45.83,2.0,54.0,75.0,1.0,25.0,10.0,6.0,9.0,0.0,9.0,8.33,75.00,54.00,18.52,5.0,48.0,93.0,5.0,17.0,14.0,6.0,8.0,0.0,8.0,11.62,18.60,9.60,29.17,3.0
24,Ashutosh Sharma,84d9c311,Delhi Capitals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Ashwani Kumar,d45c29b1,Mumbai Indians,60.0,102.0,6.0,22.0,18.0,3.0,10.0,0.0,10.0,10.20,17.00,10.00,30.00,3.0,6.0,6.0,1.0,3.0,1.0,1.0,1.0,0.0,1.0,6.00,6.00,6.00,16.67,6.0,48.0,81.0,4.0,16.0,14.0,3.0,8.0,0.0,8.0,10.12,20.25,12.00,29.17,3.0,6.0,15.0,1.0,3.0,3.0,1.0,1.0,0.0,1.0,15.00,15.00,6.00,50.00,2.0
26,Auqib Nabi,7c3c0337,Delhi Capitals,78.0,149.0,0.0,24.0,21.0,5.0,13.0,0.0,13.0,11.46,NaN,NaN,26.92,3.0,72.0,139.0,0.0,22.0,19.0,5.0,12.0,0.0,12.0,11.58,0.00,0.00,26.39,3.0,6.0,10.0,0.0,2.0,2.0,1.0,1.0,0.0,1.0,10.00,0.00,0.00,33.33,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
27,Avesh Khan,eef2536f,Lucknow Super Giants,148.0,273.0,6.0,42.0,39.0,7.0,24.0,4.0,24.4,11.07,45.50,24.67,26.35,3.0,24.0,66.0,0.0,5.0,11.0,4.0,4.0,0.0,4.0,16.50,0.00,0.00,45.83,2.0,84.0,142.0,3.0,25.0,20.0,7.0,14.0,0.0,14.0,10.14,47.33,28.00,23.81,4.0,40.0,65.0,3.0,12.0,8.0,5.0,6.0,4.0,6.4,9.75,21.67,13.33,20.00,5.0
28,Azmatullah Omarzai,8f6dd463,Punjab Kings,66.0,103.0,3.0,23.0,14.0,3.0,11.0,0.0,11.0,9.36,34.33,22.00,21.21,4.0,30.0,53.0,1.0,10.0,7.0,3.0,5.0,0.0,5.0,10.60,53.00,30.00,23.33,4.0,18.0,29.0,1.0,6.0,4.0,2.0,3.0,0.0,3.0,9.67,29.00,18.00,22.22,4.0,18.0,21.0,1.0,7.0,3.0,2.0,3.0,0.0,3.0,7.00,21.00,18.00,16.67,6.0
29,B Kumar,2e81a32d,Royal Challengers Bengaluru,330.0,444.0,24.0,124.0,56.0,14.0,55.0,0.0,55.0,8.07,18.50,13.75,16.97,5.0,180.0,213.0,15.0,91.0,31.0,14.0,30.0,0.0,30.0,7.10,14.20,12.00,17.22,5.0,30.0,49.0,1.0,9.0,7.0,5.0,5.0,0.0,5.0,9.80,49.00,30.00,23.33,4.0,120.0,182.0,8.0,24.0,18.0,12.0,20.0,0.0,20.0,9.10,22.75,15.00,15.00,6.0
30,B Muzarabani,449f4e3c,Kolkata Knight Riders,42.0,75.0,4.0,12.0,12.0,2.0,7.0,0.0,7.0,10.71,18.75,10.50,28.57,3.0,18.0,40.0,0.0,5.0,7.0,2.0,3.0,0.0,3.0,13.33,0.00,0.00,38.89,2.0,12.0,10.0,2.0,3.0,0.0,1.0,2.0,0.0,2.0,5.00,5.00,6.00,0.00,0.0,12.0,25.0,2.0,4.0,5.0,2.0,2.0,0.0,2.0,12.50,12.50,6.00,41.67,2.0
31,B Sai Sudharsan,d5130a30,Gujarat Titans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,BJ Dwarshuis,e1b9f3a9,Punjab Kings,24.0,51.0,1.0,6.0,7.0,1.0,4.0,0.0,4.0,12.75,51.00,24.00,29.17,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,18.0,34.0,0.0,4.0,4.0,1.0,3.0,0.0,3.0,11.33,0.00,0.00,22.22,4.0,6.0,17.0,1.0,2.0,3.0,1.0,1.0,0.0,1.0,17.00,17.00,6.00,50.00,2.0
33,Brijesh Sharma,133bbd61,Rajasthan Royals,233.0,375.0,13.0,73.0,53.0,11.0,38.0,5.0,38.5,9.66,28.85,17.92,22.75,4.0,60.0,115.0,1.0,21.0,21.0,8.0,10.0,0.0,10.0,11.50,115.00,60.00,35.00,2.0,90.0,114.0,4.0,23.0,12.0,9.0,15.0,0.0,15.0,7.60,28.50,22.50,13.33,7.0,83.0,146.0,8.0,29.0,20.0,10.0,13.0,5.0,13.5,10.55,18.25,10.38,24.10,4.0
34,C Bosch,172dff15,Mumbai Indians,121.0,195.0,12.0,44.0,26.0,6.0,20.0,1.0,20.1,9.67,16.25,10.08,21.49,4.0,12.0,20.0,2.0,5.0,3.0,2.0,2.0,0.0,2.0,10.00,10.00,6.00,25.00,4.0,72.0,101.0,6.0,28.0,12.0,6.0,12.0,0.0,12.0,8.42,16.83,12.00,16.67,6.0,37.0,74.0,4.0,11.0,11.0,5.0,6.0,1.0,6.1,12.00,18.50,9.25,29.73,3.0
35,C Connolly,fe366f34,Punjab Kings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,C Green,eaa76d3c,Kolkata Knight Riders,132.0,234.0,7.0,43.0,35.0,10.0,22.0,0.0,22.0,10.64,33.43,18.86,26.52,3.0,55.0,102.0,2.0,19.0,17.0,7.0,9.0,1.0,9.1,11.13,51.00,27.50,30.91,3.0,65.0,107.0,4.0,20.0,14.0,9.0,10.0,5.0,10.5,9.88,26.75,16.25,21.54,4.0,12.0,25.0,1.0,4.0,4.0,2.0,2.0,0.0,2.0,12.50,25.00,12.00,33.33,3.0
37,CV Varun,5b7ab5a9,Kolkata Knight Riders,246.0,360.0,11.0,77.0,47.0,11.0,41.0,0.0,41.0,8.78,32.73,22.36,19.11,5.0,12.0,40.0,0.0,3.0,8.0,2.0,2.0,0.0,2.0,20.00,0.00,0.00,66.67,1.0,210.0,266.0,9.0,68.0,31.0,11.0,35.0,0.0,35.0,7.60,29.56,23.33,14.76,6.0,24.0,54.0,2.0,6.0,8.0,4.0,4.0,0.0,4.0,13.50,27.00,12.00,33.33,3.0
38,D Brevis,844e79d1,Chennai Super Kings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,D Ferreira,f0af99a7,Rajasthan Royals,18.0,41.0,1.0,2.0,6.0,3.0,3.0,0.0,3.0,13.67,41.00,18.00,33.33,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,12.0,25.0,1.0,2.0,4.0,2.0,2.0,0.0,2.0,12.50,25.00,12.00,33.33,3.0,6.0,16.0,0.0,0.0,2.0,1.0,1.0,0.0,1.0,16.00,0.00,0.00,33.33,3.0
40,D Madushanka,de7d833e,Sunrisers Hyderabad,24.0,36.0,1.0,8.0,4.0,1.0,4.0,0.0,4.0,9.00,36.00,24.00,16.67,5.0,12.0,16.0,1.0,6.0,2.0,1.0,2.0,0.0,2.0,8.00,16.00,12.00,16.67,6.0,12.0,20.0,0.0,2.0,2.0,1.0,2.0,0.0,2.0,10.00,0.00,0.00,16.67,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
41,D Padikkal,2c25d4f5,Royal Challengers Bengaluru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,DA Miller,d67d5f00,Delhi Capitals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,DA Payne,6c79c098,Sunrisers Hyderabad,30.0,70.0,2.0,5.0,11.0,2.0,5.0,0.0,5.0,14.00,35.00,15.00,36.67,2.0,12.0,43.0,0.0,1.0,8.0,2.0,2.0,0.0,2.0,21.50,0.00,0.00,66.67,1.0,18.0,27.0,2.0,4.0,3.0,2.0,3.0,0.0,3.0,9.00,13.50,9.00,16.67,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
44,DL Chahar,23eeb873,Mumbai Indians,153.0,265.0,8.0,57.0,41.0,8.0,25.0,3.0,25.3,10.39,33.12,19.12,26.80,3.0,102.0,155.0,6.0,48.0,28.0,8.0,17.0,0.0,17.0,9.12,25.83,17.00,27.45,3.0,18.0,44.0,0.0,3.0,6.0,3.0,3.0,0.0,3.0,14.67,0.00,0.00,33.33,3.0,33.0,66.0,2.0,6.0,7.0,5.0,5.0,3.0,5.3,12.00,33.00,16.50,21.21,4.0
45,DS Rathi,13fc5c6d,Lucknow Super Giants,234.0,397.0,5.0,54.0,50.0,10.0,39.0,0.0,39.0,10.18,79.40,46.80,21.37,4.0,48.0,89.0,2.0,13.0,13.0,7.0,8.0,0.0,8.0,11.12,44.50,24.00,27.08,3.0,162.0,258.0,2.0,35.0,31.0,10.0,27.0,0.0,27.0,9.56,129.00,81.00,19.14,5.0,24.0,50.0,1.0,6.0,6.0,4.0,4.0,0.0,4.0,12.50,50.00,24.00,25.00,4.0
46,DV Malewar,9e6032fa,Mumbai Indians,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Dhruv Jurel,bcf325d2,Rajasthan Royals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,E Malinga,5750bcb4,Sunrisers Hyderabad,302.0,467.0,19.0,105.0,60.0,14.0,50.0,2.0,50.2,9.28,24.58,15.89,19.87,5.0,108.0,157.0,5.0,44.0,21.0,12.0,18.0,0.0,18.0,8.72,31.40,21.60,19.44,5.0,102.0,141.0,7.0,34.0,15.0,13.0,17.0,0.0,17.0,8.29,20.14,14.57,14.71,6.0,92.0,169.0,7.0,27.0,24.0,12.0,15.0,2.0,15.2,11.02,24.14,13.14,26.09,3.0
49,FH Allen,bf74b130,Kolkata Knight Riders,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,GD Phillips,9a46c4e5,Gujarat Titans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,GF Linde,e5437608,Lucknow Super Giants,37.0,55.0,1.0,10.0,8.0,3.0,6.0,1.0,6.1,8.92,55.00,37.00,21.62,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,36.0,51.0,1.0,10.0,7.0,3.0,6.0,0.0,6.0,8.50,51.00,36.00,19.44,5.0,1.0,4.0,0.0,0.0,1.0,1.0,0.0,1.0,0.1,24.00,0.00,0.00,100.00,1.0
52,Gurjapneet Singh,cc61ee8f,Chennai Super Kings,151.0,233.0,4.0,46.0,28.0,8.0,25.0,1.0,25.1,9.26,58.25,37.75,18.54,5.0,12.0,14.0,0.0,4.0,2.0,2.0,2.0,0.0,2.0,7.00,0.00,0.00,16.67,6.0,96.0,147.0,2.0,31.0,18.0,7.0,16.0,0.0,16.0,9.19,73.50,48.00,18.75,5.0,43.0,72.0,2.0,11.0,8.0,7.0,7.0,1.0,7.1,10.05,36.00,21.50,18.60,5.0
53,H Klaasen,235c2bb6,Sunrisers Hyderabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,HH Pandya,dbe50b21,Mumbai Indians,136.0,259.0,4.0,39.0,38.0,9.0,22.0,4.0,22.4,11.43,64.75,34.00,27.94,3.0,44.0,107.0,1.0,16.0,20.0,6.0,7.0,2.0,7.2,14.59,107.00,44.00,45.45,2.0,76.0,110.0,2.0,20.0,12.0,6.0,12.0,4.0,12.4,8.68,55.00,38.00,15.79,6.0,16.0,42.0,1.0,3.0,6.0,3.0,2.0,4.0,2.4,15.75,42.00,16.00,37.50,2.0
55,HV Patel,f986ca1a,Sunrisers Hyderabad,82.0,148.0,0.0,15.0,21.0,5.0,13.0,4.0,13.4,10.83,NaN,NaN,25.61,3.0,6.0,21.0,0.0,1.0,4.0,1.0,1.0,0.0,1.0,21.00,0.00,0.00,66.67,1.0,60.0,96.0,0.0,9.0,12.0,5.0,10.0,0.0,10.0,9.60,0.00,0.00,20.00,5.0,16.0,31.0,0.0,5.0,5.0,3.0,2.0,4.0,2.4,11.62,0.00,0.00,31.25,3.0
56,Harpreet Brar,c05edf8e,Punjab Kings,48.0,60.0,2.0,16.0,7.0,2.0,8.0,0.0,8.0,7.50,30.00,24.00,14.58,6.0,18.0,21.0,1.0,9.0,3.0,2.0,3.0,0.0,3.0,7.00,21.00,18.00,16.67,6.0,30.0,39.0,1.0,7.0,4.0,2.0,5.0,0.0,5.0,7.80,39.00,30.00,13.33,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
57,Harsh Dubey,25228673,Sunrisers Hyderabad,132.0,228.0,8.0,36.0,30.0,8.0,22.0,0.0,22.0,10.36,28.50,16.50,22.73,4.0,42.0,70.0,1.0,12.0,10.0,5.0,7.0,0.0,7.0,10.00,70.00,42.00,23.81,4.0,60.0,116.0,2.0,16.0,15.0,6.0,10.0,0.0,10.0,11.60,58.00,30.00,25.00,4.0,30.0,42.0,5.0,8.0,5.0,4.0,5.0,0.0,5.0,8.40,8.40,6.00,16.67,6.0
58,Himmat Singh,ebcfef83,Lucknow Super Giants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Ishan Kishan,752f7486,Sunrisers Hyderabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,J Overton,59559bc2,Chennai Super Kings,168.0,249.0,14.0,55.0,30.0,10.0,28.0,0.0,28.0,8.89,17.79,12.00,17.86,5.0,6.0,17.0,0.0,0.0,2.0,1.0,1.0,0.0,1.0,17.00,0.00,0.00,33.33,3.0,96.0,121.0,9.0,34.0,14.0,9.0,16.0,0.0,16.0,7.56,13.44,10.67,14.58,6.0,66.0,111.0,5.0,21.0,14.0,8.0,11.0,0.0,11.0,10.09,22.20,13.20,21.21,4.0
61,JA Duffy,dadbdb68,Royal Challengers Bengaluru,96.0,186.0,6.0,38.0,29.0,4.0,16.0,0.0,16.0,11.62,31.00,16.00,30.21,3.0,60.0,120.0,5.0,27.0,20.0,4.0,10.0,0.0,10.0,12.00,24.00,12.00,33.33,3.0,24.0,31.0,1.0,7.0,4.0,3.0,4.0,0.0,4.0,7.75,31.00,24.00,16.67,6.0,12.0,35.0,0.0,4.0,5.0,2.0,2.0,0.0,2.0,17.50,0.00,0.00,41.67,2.0
62,JC Archer,5574750c,Rajasthan Royals,312.0,456.0,21.0,140.0,72.0,14.0,52.0,0.0,52.0,8.77,21.71,14.86,23.08,4.0,174.0,269.0,11.0,90.0,46.0,14.0,29.0,0.0,29.0,9.28,24.45,15.82,26.44,3.0,48.0,56.0,3.0,21.0,9.0,7.0,8.0,0.0,8.0,7.00,18.67,16.00,18.75,5.0,90.0,131.0,7.0,29.0,17.0,11.0,15.0,0.0,15.0,8.73,18.71,12.86,18.89,5.0
63,JC Buttler,99b75528,Gujarat Titans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
player_bowling_stats_df[player_bowling_stats_df["player_name"].str.contains("Archer")]

,player_name,id,team,balls_bowled,runs_conceded,wickets,dot_balls,boundaries,innings_bowled,over,ball,overs_bowled,economy,bowling_average,bowling_strike_rate,boundary_pct,balls_per_boundary,pp_balls_bowled,pp_runs_conceded,pp_wickets,pp_dot_balls,pp_boundaries,pp_innings_bowled,pp_over,pp_ball,pp_overs_bowled,pp_economy,pp_bowling_average,pp_bowling_strike_rate,pp_boundary_pct,pp_balls_per_boundary,middle_balls_bowled,middle_runs_conceded,middle_wickets,middle_dot_balls,middle_boundaries,middle_innings_bowled,middle_over,middle_ball,middle_overs_bowled,middle_economy,middle_bowling_average,middle_bowling_strike_rate,middle_boundary_pct,middle_balls_per_boundary,death_balls_bowled,death_runs_conceded,death_wickets,death_dot_balls,death_boundaries,death_innings_bowled,death_over,death_ball,death_overs_bowled,death_economy,death_bowling_average,death_bowling_strike_rate,death_boundary_pct,death_balls_per_boundary
62,JC Archer,5574750c,Rajasthan Royals,312.0,456.0,21.0,140.0,72.0,14.0,52.0,0.0,52.0,8.77,21.71,14.86,23.08,4.0,174.0,269.0,11.0,90.0,46.0,14.0,29.0,0.0,29.0,9.28,24.45,15.82,26.44,3.0,48.0,56.0,3.0,21.0,9.0,7.0,8.0,0.0,8.0,7.0,18.67,16.0,18.75,5.0,90.0,131.0,7.0,29.0,17.0,11.0,15.0,0.0,15.0,8.73,18.71,12.86,18.89,5.0

In [58]:
player_bowling_stats_df[player_bowling_stats_df["player_name"].str.contains("Rabada")]

,player_name,id,team,balls_bowled,runs_conceded,wickets,dot_balls,boundaries,innings_bowled,over,ball,overs_bowled,economy,bowling_average,bowling_strike_rate,boundary_pct,balls_per_boundary,pp_balls_bowled,pp_runs_conceded,pp_wickets,pp_dot_balls,pp_boundaries,pp_innings_bowled,pp_over,pp_ball,pp_overs_bowled,pp_economy,pp_bowling_average,pp_bowling_strike_rate,pp_boundary_pct,pp_balls_per_boundary,middle_balls_bowled,middle_runs_conceded,middle_wickets,middle_dot_balls,middle_boundaries,middle_innings_bowled,middle_over,middle_ball,middle_overs_bowled,middle_economy,middle_bowling_average,middle_bowling_strike_rate,middle_boundary_pct,middle_balls_per_boundary,death_balls_bowled,death_runs_conceded,death_wickets,death_dot_balls,death_boundaries,death_innings_bowled,death_over,death_ball,death_overs_bowled,death_economy,death_bowling_average,death_bowling_strike_rate,death_boundary_pct,death_balls_per_boundary
71,K Rabada,e62dd25d,Gujarat Titans,322.0,493.0,24.0,142.0,76.0,14.0,53.0,4.0,53.4,9.19,20.54,13.42,23.6,4.0,222.0,342.0,17.0,102.0,55.0,14.0,37.0,0.0,37.0,9.24,20.12,13.06,24.77,4.0,40.0,59.0,3.0,18.0,10.0,7.0,6.0,4.0,6.4,8.85,19.67,13.33,25.0,4.0,60.0,92.0,4.0,22.0,11.0,10.0,10.0,0.0,10.0,9.2,23.0,15.0,18.33,5.0

In [55]:
player_bowling_stats_df[player_bowling_stats_df["player_name"].str.contains("Holder")]

,player_name,id,team,balls_bowled,runs_conceded,wickets,dot_balls,boundaries,innings_bowled,over,ball,overs_bowled,economy,bowling_average,bowling_strike_rate,boundary_pct,balls_per_boundary,pp_balls_bowled,pp_runs_conceded,pp_wickets,pp_dot_balls,pp_boundaries,pp_innings_bowled,pp_over,pp_ball,pp_overs_bowled,pp_economy,pp_bowling_average,pp_bowling_strike_rate,pp_boundary_pct,pp_balls_per_boundary,middle_balls_bowled,middle_runs_conceded,middle_wickets,middle_dot_balls,middle_boundaries,middle_innings_bowled,middle_over,middle_ball,middle_overs_bowled,middle_economy,middle_bowling_average,middle_bowling_strike_rate,middle_boundary_pct,middle_balls_per_boundary,death_balls_bowled,death_runs_conceded,death_wickets,death_dot_balls,death_boundaries,death_innings_bowled,death_over,death_ball,death_overs_bowled,death_economy,death_bowling_average,death_bowling_strike_rate,death_boundary_pct,death_balls_per_boundary
68,JO Holder,0f721006,Gujarat Titans,170.0,208.0,13.0,68.0,26.0,8.0,28.0,2.0,28.2,7.34,16.0,13.08,15.29,6.0,6.0,8.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,8.0,0.0,0.0,16.67,6.0,138.0,175.0,9.0,57.0,22.0,8.0,23.0,0.0,23.0,7.61,19.44,15.33,15.94,6.0,26.0,25.0,4.0,10.0,3.0,5.0,4.0,2.0,4.2,5.77,6.25,6.5,11.54,8.0

In [56]:
player_bowling_stats_df[player_bowling_stats_df["player_name"].str.contains("Bumrah")]

,player_name,id,team,balls_bowled,runs_conceded,wickets,dot_balls,boundaries,innings_bowled,over,ball,overs_bowled,economy,bowling_average,bowling_strike_rate,boundary_pct,balls_per_boundary,pp_balls_bowled,pp_runs_conceded,pp_wickets,pp_dot_balls,pp_boundaries,pp_innings_bowled,pp_over,pp_ball,pp_overs_bowled,pp_economy,pp_bowling_average,pp_bowling_strike_rate,pp_boundary_pct,pp_balls_per_boundary,middle_balls_bowled,middle_runs_conceded,middle_wickets,middle_dot_balls,middle_boundaries,middle_innings_bowled,middle_over,middle_ball,middle_overs_bowled,middle_economy,middle_bowling_average,middle_bowling_strike_rate,middle_boundary_pct,middle_balls_per_boundary,death_balls_bowled,death_runs_conceded,death_wickets,death_dot_balls,death_boundaries,death_innings_bowled,death_over,death_ball,death_overs_bowled,death_economy,death_bowling_average,death_bowling_strike_rate,death_boundary_pct,death_balls_per_boundary
66,JJ Bumrah,462411b3,Mumbai Indians,294.0,410.0,4.0,105.0,55.0,13.0,49.0,0.0,49.0,8.37,102.5,73.5,18.71,5.0,144.0,211.0,2.0,57.0,32.0,13.0,24.0,0.0,24.0,8.79,105.5,72.0,22.22,4.0,72.0,93.0,1.0,26.0,10.0,10.0,12.0,0.0,12.0,7.75,93.0,72.0,13.89,7.0,78.0,106.0,1.0,22.0,13.0,9.0,13.0,0.0,13.0,8.15,106.0,78.0,16.67,6.0

In [57]:
player_bowling_stats_df[player_bowling_stats_df["player_name"].str.contains("Narine")]

,player_name,id,team,balls_bowled,runs_conceded,wickets,dot_balls,boundaries,innings_bowled,over,ball,overs_bowled,economy,bowling_average,bowling_strike_rate,boundary_pct,balls_per_boundary,pp_balls_bowled,pp_runs_conceded,pp_wickets,pp_dot_balls,pp_boundaries,pp_innings_bowled,pp_over,pp_ball,pp_overs_bowled,pp_economy,pp_bowling_average,pp_bowling_strike_rate,pp_boundary_pct,pp_balls_per_boundary,middle_balls_bowled,middle_runs_conceded,middle_wickets,middle_dot_balls,middle_boundaries,middle_innings_bowled,middle_over,middle_ball,middle_overs_bowled,middle_economy,middle_bowling_average,middle_bowling_strike_rate,middle_boundary_pct,middle_balls_per_boundary,death_balls_bowled,death_runs_conceded,death_wickets,death_dot_balls,death_boundaries,death_innings_bowled,death_over,death_ball,death_overs_bowled,death_economy,death_bowling_average,death_bowling_strike_rate,death_boundary_pct,death_balls_per_boundary
161,SP Narine,9d430b40,Kolkata Knight Riders,306.0,339.0,15.0,131.0,40.0,13.0,51.0,0.0,51.0,6.65,22.6,20.4,13.07,7.0,72.0,96.0,2.0,33.0,16.0,10.0,12.0,0.0,12.0,8.0,48.0,36.0,22.22,4.0,180.0,194.0,4.0,68.0,18.0,13.0,30.0,0.0,30.0,6.47,48.5,45.0,10.0,10.0,54.0,49.0,9.0,30.0,6.0,9.0,9.0,0.0,9.0,5.44,5.44,6.0,11.11,9.0

In [ ]:
def calculate_player_stats(deliveries_df, players_df):
    """
    Calculates overall season stats for every player from the deliveries DataFrame.
    Returns a single player_stats_df with one row per player containing:
      - Batting stats
      - Bowling stats
      - Fielding stats
    All joined to the players table on player_name.

    Corrections applied:
      - Wides excluded from balls faced (no-balls count as faced)
      - Runs conceded includes wides and no-balls (but not byes or leg byes)
      - Dismissals counted via player_dismissed (catches non-striker run outs too)
    """
    


    # -------------------------------------------------------
    # BOWLING STATS
    # grouped by bowler
    # -------------------------------------------------------

    # A legal delivery excludes wides and no-balls
    deliveries_df["is_legal"] = (
        (deliveries_df["extra_type"] != "wides") & (deliveries_df["extra_type"] != "noballs")
    ).astype(int)

    # Runs conceded by bowler = runs off bat + wides + no-balls
    # Byes and leg byes are NOT the bowler's fault
    deliveries_df["runs_conceded"] = (
        deliveries_df["runs_off_bat"].fillna(0) +
        deliveries_df["wides"].fillna(0) +
        deliveries_df["noballs"].fillna(0)
    )

    # Wickets credited to bowler — excludes run outs, retired hurt, obstructions
    deliveries_df["bowler_wicket"] = (
        deliveries_df["wicket_type"].notna() &
        ~deliveries_df["wicket_type"].isin([
            "run out", "retired hurt", "retired out", "obstructing the field"
        ])
    ).astype(int)

    # Dot balls = legal delivery where total runs == 0
    deliveries_df["total_runs"] = deliveries_df["runs_off_bat"] + deliveries_df["extras"]
    deliveries_df["is_dot"] = (
        (deliveries_df["is_legal"] == 1) & (deliveries_df["total_runs"] == 0)
    ).astype(int)

    bowling_stats = deliveries_df.groupby("bowler").agg(
        balls_bowled   = ("is_legal",        "sum"),
        runs_conceded  = ("runs_conceded",    "sum"),
        wickets        = ("bowler_wicket",    "sum"),
        dot_balls      = ("is_dot",           "sum"),
        innings_bowled = ("match_id",         "nunique")
    ).reset_index().rename(columns={"bowler": "player_name"})

    # Overs bowled (balls / 6, rounded to 1 decimal)
    bowling_stats["overs_bowled"] = (
        bowling_stats["balls_bowled"] / 6
    ).round(1)

    # Economy rate = runs conceded per over
    bowling_stats["economy"] = (
        bowling_stats["runs_conceded"] / bowling_stats["overs_bowled"]
    ).round(2)

    # Bowling average = runs conceded per wicket
    bowling_stats["bowling_average"] = (
        bowling_stats["runs_conceded"] / bowling_stats["wickets"].replace(0, float("nan"))
    ).round(2)

    # Bowling strike rate = balls bowled per wicket
    bowling_stats["bowling_strike_rate"] = (
    bowling_stats["balls_bowled"] / bowling_stats["wickets"].replace(0, float("nan"))
    ).round(2)


    # -------------------------------------------------------
    # FIELDING STATS
    # -------------------------------------------------------

    # Caught and bowled — catch credited to the bowler
    catches_cb = deliveries_df[
        deliveries_df["wicket_type"] == "caught and bowled"
    ].groupby("bowler").size().reset_index()
    catches_cb.columns = ["player_name", "catches_cb"]

    # Normal catches — fielder is in other_player_dismissed
    catches_normal = deliveries_df[
        deliveries_df["wicket_type"] == "caught"
    ].groupby("other_player_dismissed").size().reset_index()
    catches_normal.columns = ["player_name", "catches_normal"]

    # Run outs — credited to fielder in other_player_dismissed
    run_outs = deliveries_df[
        deliveries_df["wicket_type"] == "run out"
    ].groupby("other_player_dismissed").size().reset_index()
    run_outs.columns = ["player_name", "run_outs"]

    # Stumpings — credited to wicketkeeper in other_player_dismissed
    stumpings = deliveries_df[
        deliveries_df["wicket_type"] == "stumped"
    ].groupby("other_player_dismissed").size().reset_index()
    stumpings.columns = ["player_name", "stumpings"]

    # Combine all fielding stats
    fielding_stats = (catches_normal
        .merge(catches_cb,  on="player_name", how="outer")
        .merge(run_outs,    on="player_name", how="outer")
        .merge(stumpings,   on="player_name", how="outer")
        .fillna(0)
    )
    fielding_stats["catches"] = (
        fielding_stats["catches_normal"] + fielding_stats["catches_cb"]
    ).astype(int)
    fielding_stats = fielding_stats[["player_name", "catches", "run_outs", "stumpings"]]


    # -------------------------------------------------------
    # JOIN EVERYTHING TOGETHER
    # -------------------------------------------------------
    player_stats_df = (players_df
        .merge(batting_stats,  on="player_name", how="left")
        .merge(bowling_stats,  on="player_name", how="left")
        .merge(fielding_stats, on="player_name", how="left")
        .fillna(0)
    )

    print(f"✓ Player stats calculated: {len(player_stats_df)} players")
    print(f"  Columns: {list(player_stats_df.columns)}")

    return player_stats_df

In [ ]:
player_stats_df = calculate_player_stats(deliveries_df, players_df)

In [ ]:
def calculate_innings_stats(deliveries_df):
    """
    Calculates per-innings stats for each player.
    Used to derive:
      Batting: highest score (with not out *), 50s, 100s
      Bowling: best bowling figures, 4 wicket hauls, 5 wicket hauls

    Returns:
      batting_innings_df : one row per batter per match per innings
      bowling_innings_df : one row per bowler per match per innings
    """

    # -------------------------------------------------------
    # BATTING INNINGS STATS
    # group by match + innings + striker
    # -------------------------------------------------------

    # Reuse ball_faced and is_four, is_six if already calculated
    # otherwise calculate them here too
    if "ball_faced" not in deliveries_df.columns:
        deliveries_df["ball_faced"] = deliveries_df["wides"].isna().astype(int)
    if "is_four" not in deliveries_df.columns:
        deliveries_df["is_four"] = (deliveries_df["runs_off_bat"] == 4).astype(int)
    if "is_six" not in deliveries_df.columns:
        deliveries_df["is_six"] = (deliveries_df["runs_off_bat"] == 6).astype(int)

    batting_innings_df = deliveries_df.groupby(
        ["match_id", "innings", "striker"]
    ).agg(
        runs        = ("runs_off_bat", "sum"),
        balls_faced = ("ball_faced",   "sum"),
        fours       = ("is_four",      "sum"),
        sixes       = ("is_six",       "sum"),
    ).reset_index().rename(columns={"striker": "player_name"})

    # Determine if batter was dismissed in this innings
    # by checking if their name appears in player_dismissed
    # for the same match and innings
    dismissals = (deliveries_df[deliveries_df["player_dismissed"].notna()]
                    [["match_id", "innings", "player_dismissed"]]
                    .drop_duplicates()
                    .rename(columns={"player_dismissed": "player_name"}))
    dismissals["was_dismissed"] = True

    batting_innings_df = batting_innings_df.merge(
        dismissals,
        on=["match_id", "innings", "player_name"],
        how="left"
    )
    batting_innings_df["was_dismissed"] = batting_innings_df["was_dismissed"].fillna(False)

    # Format highest score with * for not out
    batting_innings_df["score_str"] = batting_innings_df.apply(
        lambda row: str(int(row["runs"])) if row["was_dismissed"] else str(int(row["runs"])) + "*",
        axis=1
    )

    # Flag 50s and 100s
    # 50 = runs >= 50 and < 100
    # 100 = runs >= 100
    batting_innings_df["is_fifty"]   = (
        (batting_innings_df["runs"] >= 50) & (batting_innings_df["runs"] < 100)
    ).astype(int)
    batting_innings_df["is_hundred"] = (
        batting_innings_df["runs"] >= 100
    ).astype(int)


    # -------------------------------------------------------
    # BOWLING INNINGS STATS
    # group by match + innings + bowler
    # -------------------------------------------------------

    if "is_legal" not in deliveries_df.columns:
        deliveries_df["is_legal"] = (
            deliveries_df["wides"].isna() & deliveries_df["noballs"].isna()
        ).astype(int)

    if "runs_conceded" not in deliveries_df.columns:
        deliveries_df["runs_conceded"] = (
            deliveries_df["runs_off_bat"].fillna(0) +
            deliveries_df["wides"].fillna(0) +
            deliveries_df["noballs"].fillna(0)
        )

    if "bowler_wicket" not in deliveries_df.columns:
        deliveries_df["bowler_wicket"] = (
            deliveries_df["wicket_type"].notna() &
            ~deliveries_df["wicket_type"].isin([
                "run out", "retired hurt", "retired out", "obstructing the field"
            ])
        ).astype(int)

    bowling_innings_df = deliveries_df.groupby(
        ["match_id", "innings", "bowler"]
    ).agg(
        balls_bowled  = ("is_legal",       "sum"),
        runs_conceded = ("runs_conceded",  "sum"),
        wickets       = ("bowler_wicket",  "sum"),
    ).reset_index().rename(columns={"bowler": "player_name"})

    # Flag 4 wicket and 5 wicket hauls
    bowling_innings_df["is_four_wickets"] = (
        (bowling_innings_df["wickets"] >= 4) & (bowling_innings_df["wickets"] < 5)
    ).astype(int)
    bowling_innings_df["is_five_wickets"] = (
        bowling_innings_df["wickets"] >= 5
    ).astype(int)

    # Best bowling figures as string e.g. "4/22"
    bowling_innings_df["figures_str"] = (
        bowling_innings_df["wickets"].astype(int).astype(str) + "/" +
        bowling_innings_df["runs_conceded"].astype(int).astype(str)
    )

    return batting_innings_df, bowling_innings_df


def calculate_milestones(batting_innings_df, bowling_innings_df):
    """
    Aggregates innings-level data into per-player milestone stats:
      Batting : highest_score, fifties, hundreds
      Bowling : best_figures, four_wicket_hauls, five_wicket_hauls
    """

    # -------------------------------------------------------
    # BATTING MILESTONES
    # -------------------------------------------------------

    # Highest score — sort by runs desc, not out ranks above out for equal runs
    batting_innings_df["not_out"] = (~batting_innings_df["was_dismissed"]).astype(int)

    highest_score = (batting_innings_df
        .sort_values(["runs", "not_out"], ascending=[False, False])
        .groupby("player_name")
        .first()[["score_str"]]
        .reset_index()
        .rename(columns={"score_str": "highest_score"})
    )

    # Count 50s and 100s per player
    batting_milestones = batting_innings_df.groupby("player_name").agg(
        fifties  = ("is_fifty",   "sum"),
        hundreds = ("is_hundred", "sum"),
    ).reset_index()

    batting_milestones = batting_milestones.merge(highest_score, on="player_name", how="left")


    # -------------------------------------------------------
    # BOWLING MILESTONES
    # -------------------------------------------------------

    # Best bowling figures — sort by wickets desc, then runs asc (fewer runs is better)
    best_figures = (bowling_innings_df
        .sort_values(["wickets", "runs_conceded"], ascending=[False, True])
        .groupby("player_name")
        .first()[["figures_str"]]
        .reset_index()
        .rename(columns={"figures_str": "best_figures"})
    )

    # Count 4 and 5 wicket hauls per player
    bowling_milestones = bowling_innings_df.groupby("player_name").agg(
        four_wicket_hauls = ("is_four_wickets", "sum"),
        five_wicket_hauls = ("is_five_wickets", "sum"),
    ).reset_index()

    bowling_milestones = bowling_milestones.merge(best_figures, on="player_name", how="left")

    return batting_milestones, bowling_milestones

In [ ]:
batting_innings_df, bowling_innings_df = calculate_innings_stats(deliveries_df)

In [ ]:
batting_milestones, bowling_milestones = calculate_milestones(batting_innings_df, bowling_innings_df)

In [ ]:
player_stats_df = player_stats_df.merge(batting_milestones, on="player_name", how='left')
player_stats_df = player_stats_df.merge(bowling_milestones, on="player_name", how='left')

In [ ]:
player_stats_df

In [ ]:
matches_df[matches_df['match_number']=='50']